### ISSUE TITLE
Inscription aux ateliers

### ISSUE THREAD

**Issue by libress** [CroissanceCommune/autonomie#227]
Bonjour,
Entrepreneur-salarié de Port Parallèle, je souhaite faire remonter une fonctionnalité d'autonomie qui pourrait être intéressante à développer.
Il s'agit des inscriptions aux ateliers de formation internes à P//.
Je constate un doublon d'inscription entre:
- un formulaire type doodle
- et l'enregistrement à la participation des ateliers sur autonomie Gestion > Ateliers

Merci de votre attention!

Bien cordialement,

Baptiste Cambon

**Comment by eheliot12** [comment]
repris par #624
