### ISSUE TITLE
Lock invoice/cancelinvoice tables on validation

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#232]
To ensure officialNumber unicity, we need to lock the tables

**Comment by tonthon** [comment]
the problem happens in very exceptional cases

**Comment by JocelynDelalande** [comment]
Utiliser les subtransactions de SQLA.

**Comment by tonthon** [comment]
https://docs.sqlalchemy.org/en/latest/orm/session_transaction.html#using-savepoint
