### ISSUE TITLE
Bug avec Iceweasel 36.0.4

### ISSUE THREAD

**Issue by libress** [CroissanceCommune/autonomie#234]
Bonjour,
Il m'est impossible de me connecter sur Autonomie via la dernière version à jour du navigateur Iceweasel 36.0.4
Bien cordialement,

**Comment by tonthon** [comment]
Je ne rencontre aucun soucis avec firefox 36.0.4 (censé être la même chose). 
Utilisez-vous des modules complémentaires dans iceweasel ? 
Dans ce cas, pourrlez-vous essayer en les désactivant ?

**Comment by libress** [comment]
Bonjour,
Effectivement c'est censé être le même navigateur.
J'ai tenté une connection en ayant désactivé l'ensemble des modules complémentaires.
Résultat nul :-/

**Comment by tonthon** [comment]
pouvez-vous m'envoyer votre login ainsi que l'url à laquelle vous vous connectez à l'adresse suivante : 
autonomie@majerti.fr

**Comment by feth** [comment]
Bonjour,

si je peux me permettre une suggestion de manip : pouvez-vous purger le
cache de firefox/iceweasel ?

Bien � vous,

Feth

**Comment by libress** [comment]
Sans problème.
Le cache de Iceweasel vient d'être purgé

Impossible néanmoins de me connecter sans navigateur privé.

Bonne journée,
