### ISSUE TITLE
libellé remise

### ISSUE THREAD

**Issue by Kaor** [CroissanceCommune/autonomie#282]
Bonjour,
j'ai l'impression que le libellé d'une remise n'apparait plus dans le pdf.
Merci

**Comment by Kaor** [comment]
en fait l'erreur se produit aussi pour des lignes normale, j'ai pas mal de factures avec des lignes sans texte

**Comment by tonthon** [comment]
Je ne reproduit pas le problème. Pourriez-vous nous envoyer un lien par mail ?

**Comment by tonthon** [comment]
Cela devrait être résolu désormais, merci de réouvrir le ticket si le problème réapparaît.
https://github.com/CroissanceCommune/autonomie/issues/297
