### ISSUE TITLE
Avertir que la saisie n'a pas été prise en compte dans les notes de frais

### ISSUE THREAD

**Issue by feth** [CroissanceCommune/autonomie#329]
# Comment reproduire 
- onglet 1, ouvrir autonomie, aller dans une note de frais en brouillon
- onglet 2, ouvrir autonomie, se déconnecter (simulation d'expiration de session)
- onglet 1, cliquer sur "ajouter des frais", ajouter un achat
# Ce qui se produit 

rien de visible ne se produit
# Ce qui est attendu

on voudrait une grosse fenêtre surgissante pour prévenir de l'erreur.

**Comment by tonthon** [comment]
https://github.com/CroissanceCommune/autonomie/blob/master/autonomie/static/js/main.js#L301
Devrait engendrer une violente redirection vers la page de login (pourquoi ça ne marche pas ?).

Solution plus ergonomique à envisager
1- Codifier les erreurs d'authentification dans les retours json (plutôt qu'une clé redirect)
2- Utiliser un hook sur les méthodes utilisées par marionettejs pour intégrer le popup de la boite de dialogue de login (Utiliser les outils fournis par https://github.com/CroissanceCommune/autonomie/blob/master/autonomie/static/js/main.js)
