### ISSUE TITLE
Mise à jour de l'adresse client

### ISSUE THREAD

**Issue by Kaor** [CroissanceCommune/autonomie#330]
Je fais un devis,
je l'enregistre en brouillon
je modifie l'adresse du client,
je reviens dans le devis,
la nouvelle adresse n'est pas prise en compte,
je dois désectionner le client et le reselectionner
Merci

**Comment by feth** [comment]
Bonjour,

merci de ce retour @Kaor !
À mon sens, ceci n'est pas un bug, mais un choix : l'adresse du client est enregistrée séparément pour chaque élément de facturation.
L'inconvénient, vous l'avez montré ; l'avantage est que vous pouvez facturer divers services et sites d'un même client.
On peut déduire de cela que l'ergonomie du formulaire peut être améliorée.

Sans objection ou suggesion ergonmique, je fermerai le ticket.

**Comment by tonthon** [comment]
C'est effectivement le fonctionnement qui a été demandé.
L'adresse du client est attaché directement au document et peut ainsi être modifié au besoin.
Rouvrir le ticket si il y a des propositions pour améliorer l'ergonomie
