### ISSUE TITLE
Cocher par défaut "Afficher le détail des prestations dans la sortie PDF ?"

### ISSUE THREAD

**Issue by feth** [CroissanceCommune/autonomie#340]
Je pense que 99.9999% des gens préfèrent afficher le nb de forfaits qu'ils facturent dans le PDF :-)

**Comment by feth** [comment]
(je peux faire une PR si on est d'accord)

**Comment by tonthon** [comment]
Je ne pense pas que ce soit une bonne idée de changer ce comportement.
Notamment parce que ceux qui n'affichent pas le détail ne veulent certainement pas que leur client dispose du détail de leur calcul.

**Comment by feth** [comment]
Ok alors.
