### ISSUE TITLE
masquer les notes de dépenses "extra compte commun"

### ISSUE THREAD

**Issue by vinber** [CroissanceCommune/autonomie#388]
Lorsque nous sommes plusieurs sous un compte commun, nous voyons les notes de dépenses des collègues pour toutes leurs activités et non pas seulement les notes de dépenses pour le compte commun.
## Contexte

Un compte commun avec plusieurs entrepreneurs
Chaque entrepreneur a plusieurs comptes avec des notes de dépenses attribuées à plusieurs comptes.
Visualisation des notes de dépenses
On voit les notes de dépenses (montant) de tous les comptes pour ses collègues.
## Ce qui devrait se passer

Visualiser l'ensemble de ses notes de dépenses et les dépenses de ses collègues seulement pour le compte commun
## Environnement logiciel
- versions d'autonomie concernées

autonomie en production coopalpha le 21 juillet 2016

**Comment by vinber** [comment]
Bonjour,
sur la version Autonomie v4.0.2 cela semble être ok, merci beaucoup. Vous fermez ? Je ferme ?

**Comment by tonthon** [comment]
JE m'en occupe ;)
