### ISSUE TITLE
Le filtre année sur le facture ne s'appuie pas sur la date émise

### ISSUE THREAD

**Issue by Kaor** [CroissanceCommune/autonomie#414]
Dans Gestion > Factures,
ma facture en brouillon depuis 2015 et validée en 2016 apparaît avec le filtre 2015 et non 2016, c'est fâcheux.

**Comment by tonthon** [comment]
C'est l'année fiscale à laquelle la facture est rattachée qui est utilisée, non la date de facturation.
Il manque peut être une petite indication pour rendre cela plus clair
