### ISSUE TITLE
Adresse du client avec un &amp;

### ISSUE THREAD

**Issue by Kaor** [CroissanceCommune/autonomie#440]
## Contexte
Mettre un caractère "&" dans l'adresse d'un client

## Ce qui devrait se passer
que le "&" s'affiche tout simplement

## Ce qui se passe
le "&" s'affiche "`&amp;`" lors de l'édition d'un devis, en pdf pas de soucis

**Comment by tonthon** [comment]
Correctif lors de la prochaine mise à jour (version 3.4)
