### ISSUE TITLE
Affichage des divers comptes

### ISSUE THREAD

**Issue by vinber** [CroissanceCommune/autonomie#443]
## Contexte
j'ai plusieurs comptes, quand je regarde le sélecteur, je ne vois pas le nom du compte

Quelles étapes :

1. je me connecte sur autonomie
2. je rentre dans un des comptes
3. en haut à gauche le menu déroulant est vide

## Ce qui devrait se passer

voir le nom du compte en cours

## Ce qui se passe

![capture du 2017-10-27 10-26-20](https://user-images.githubusercontent.com/890869/32094880-90b5cc4c-bb01-11e7-954c-f2bcc1b7b278.png)

## Environnement logiciel

* je ne sais pas le dire, celle en prod à coopalpha (2017-10-27)
* Firefox 56.0 (64 bits)
* ubuntu 16.04, écran hp le1901w !!!

**Comment by tonthon** [comment]
Un correctif devrait être mis en ligne rapidement

**Comment by vinber** [comment]
merci
