### ISSUE TITLE
exonération de tva, nota-bene

### ISSUE THREAD

**Issue by Cyrille37** [CroissanceCommune/autonomie#494]
Salut,

Autonomie 4.0.12

Quand on édite un devis /facture avec de l'exonération TVA et une ligne sans exonération, il y a de précisé :
> astérisque* NB : Exonération de TVA, article 283-2 du Code général des impôts

Mais l'astérisque n'est sur aucune des lignes, il devrait être présent sur la ou les lignes avec exonération.

Cheers.

**Comment by eheliot12** [comment]
l'asterisque est lié au choix du libellé par la cooperative lors de la configuration des taux de tva.
si la mention est obligatoire, il n'est pas obligatoire de la lier a une ligne
