### ISSUE TITLE
liste facture / tri par tva

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#507]
sur le site demo, quand on tire les factures par montant de tva, il semble réaliser le tri correctement sur les valeurs non-nulles. par contre les valeurs 0 s'intercalent dans les valeurs non-nulles
![image](https://user-images.githubusercontent.com/33490126/35726582-b148163a-0805-11e8-8233-16d069008895.png)

**Comment by sbodrero** [comment]
Mergé sur master pull request #755
