### ISSUE TITLE
Libellé de la configuration du champ "Aptitude"

### ISSUE THREAD

**Issue by paul-kilya** [CroissanceCommune/autonomie#525]
Le champ "Aptitude" présent dans la partie "Parcours" des fiches Gestion Sociale propose un menu déroulant qui est rempli par une option de configuration nommée "Statut du parcours".

Il faudrait renommer la configuration pour que ce soit plus parlant (le champ est en lien avec la visite médicale).

**Comment by tonthon** [comment]
Dans les différentes CAE utilisatrices d'Autonomie on trouve généralement des informations sur le statut du parcours 
Convention d'accompagnement
CAPE
Salarié 
...


D'autres (plus rares) l'utilisent pour stocker le statut de la visite médical 
Apte
Non Apte

**Comment by sbodrero** [comment]
Est que l'intitulé "Résultat de la visite médicale" pourrait convenir en remplacement de 'Aptitude' ?

**Comment by sbodrero** [comment]
Peut-on statuer sur cette issue ?
Cet intitulé satisfait-il "Résultat de la visite médicale" ?
Merci.

**Comment by paul-kilya** [comment]
Même si je ne suis pas convaincu de l'utilité de ce champs, dans la mesure où il n'a plus aucune utilité pour le parcours je pense que tu peux utiliser cet intitulé oui.

Il faudra voir comment on gère en terme de migration pour les CAE qui l'utilisait pour autre chose.

**Comment by paul-kilya** [comment]
Sinon est-ce qu'on ne gagnerait pas à carrément le supprimer ? Ou le remettre à zéro ?

**Comment by sbodrero** [comment]
Le remettre à zéro ?

**Comment by paul-kilya** [comment]
Effacer les saisies existantes des utilisateurs pour ce champ, au moins pour les CAE qui l'utilisaient pour le parcours.

**Comment by sbodrero** [comment]
Ok donc je pars sur le label "Résultat de la visite médicale" avec un script de migration qui efface la valeur actuel du champs pour les CAE qui utilise ce champ dans le parcours.
La perte d'information ne posera pas soucis ?

**Comment by paul-kilya** [comment]
Non ne fais rien pour l'instant, je soulevais juste la question. Si on efface des données je pense qu'on le fera à la main pour les CAE concernées, pas de manière automatique.

En fait j'aimerais avoir l'avis de @tonthon et @eheliot12 sur l'utilité de conserver ce champs, et si on le garde sur ce qu'on fait des données incohérentes.

**Comment by eheliot12** [comment]
quels sont les usages actuels ? 
ils font quoi de apte/non apte ? quand j'aurai les noms sur le chat, je leur demanderai l'interet

pour la rubrique visite medicale, ce qui est interessant c'est la date de la dernière visite. et des capacités de remonter des alertes sur le dépassement de la date de renouvellement

**Comment by sbodrero** [comment]
Ok donc pour l'instant on met de côté l'issue jusqu'à prise de décision ferme.
