### ISSUE TITLE
Accompagnement - Ateliers : erreur à la recherche avec un libellé accentué

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#531]
Effectuer une recherche avec un libellé accentué
On obtient une erreur 500

**Comment by JocelynDelalande** [comment]
Je n'arrive pas à reproduire en local. Par contre je constate bien le bug sur la démo.

Avec un peu de chance, c'est un bug qui n'existe plus, la démo est sur quel commit ?

**Comment by JocelynDelalande** [comment]
Merci. @tonthon tu peux clore l'issue du coup ? (je n'ai pas les droits pour).
