### ISSUE TITLE
[Gestion sociale] Amélioration de la gestion du parcours

### ISSUE THREAD

**Issue by paul-kilya** [CroissanceCommune/autonomie#533]
Reprendre le système d'historique du parcours des fiches gestion sociale pour : 

- Permettre de retrouver les détails de la situation de chaque porteur de projet à une date donnée (indispensable pour les statistiques)
- Permettre de gérer proprement le cas des porteurs de projet sortis puis revenus dans la coopérative
- Permettre de choisir la date correspondant au changement de situation
- Permettre d'ajouter d'autres éléments (paramétrables) que les contrats dans le parcours

**Comment by paul-kilya** [comment]
Pour info le système actuellement utilisé dans Winscop : 

1. La coopérative configure autant d'étapes de parcours que nécessaire en choisissant : 
   - La situation du porteur après l'affectation de cette étape à son dossier
   - Si l'étape correspond à une signature de contrat de travail ou à une sortie (pour pouvoir renseigner les champs correspondant au moment de l'affectation)
   - Les documents de fusion qui doivent être édités lors de l'affectation

2. Les permanents peuvent affecter n'importe quelle étape de parcours aux entrepreneurs en renseignant la date d'effet et (éventuellement) la date d'échéance, ainsi les informations relatives au contrat (nombre d'heures travaillées, taux horaire, objectifs de CA, etc) ou à la sortie (motif, date d'entretien, montant du solde de tout compte, etc) si besoin. Les documents de fusion rattachés sont automatiquement édités en utilisant les infos de l'étape.

3. Le parcours des porteurs correspond à une liste d'étapes classées chronologiquement et leur situation au sein de la coopérative est automatiquement déduite du parcours.

**Comment by eheliot12** [comment]
Pour faciliter la compréhension du cycle de vie contractuel, il faut que les étapes soient basées sur la situation dans la CAE.
(RGPD) dans les paramétrages de l’historisation, il faut une durée de rétention des informations après le départ de l'ES qui déclenche la destruction automatique des information après ce délai.

**Comment by paul-kilya** [comment]
Maintenant que le parcours des porteurs est opérationnel il faut modifier l'existant pour l'intégrer dans le fonctionnement de l'application.

_Ceci est une "to-do list" de ce travail qui sera complétée et mise à jour au fur et à mesure._

_____

### MIGRATION DES DONNÉES

- [ ] Insérer un jeu de données par défaut pour les étapes configurables : "Diagnostic", "Convention CAPE", "DPAE", "Contrat de travail", "Avenant contrat", et "Sortie"
- [ ] Créer un script de migration Alembic pour migrer les données correspondant au parcours depuis les tables `user_datas`, `contract_history`, `date_convention_cape_datas`, ` 	date_diagnostic_datas`, et `date_dpae_datas` vers la table `career_path`, puis supprimer les champs et tables migrés et devenus inutiles
- [ ] Modifier les modèles et schémas en conséquence

:question: Faut-il ajouter un type d'étape "Avenant" et un champs "Numéro d'avenant" dans le parcours ?

### SITUATION CAE
- [ ] Ajouter une fonction pour déduire la situation du porteur dans la CAE à une date donnée depuis son parcours
- [ ] Ajouter un traitement de mise à jour de la situation dans `user_datas` à chaque enregistrement du parcours

### FICHES GESTION SOCIALE
- [ ] Mettre le menu déroulant de la situation actuelle dans la CAE en lecture seule (ou le remplacer par un simple libellé)
- [ ] Déplacer les champs concernant le prescripteur, les objectifs/aptitudes, et la visite médicale dans un autre onglet [lequel ?]
- [ ] Supprimer les onglet "Parcours" et "Sortie"

:question: Est-ce que la date d'info. coll. et le motif de non admission doivent être laissés tels-quels et déplacés ou transformés en étapes de parcours ?

### HISTORIQUE
- [ ] Supprimer le menu sur les fiches utilisateurs
- [ ] Supprimer le code correspondant dans `models/user/userdatas.py`, `views/userdatas/userdatas.py`, `views/userdatas/routes.py`, et `templates\user\history.mako`

:question: Faut-il migrer également les données de la table `cae_situation_change` ? Si oui, avec quelles étapes ? Si non, que fait-on de ces données ?
:question: Que fait-on de la partie "Documents générés depuis Autonomie" de l'historique actuel ?

### DOCUMENTS DE FUSION
- [ ] **[A VOIR]**

### STATISTIQUES
- [ ] **[A VOIR]**

**Comment by paul-kilya** [comment]
Sur un nouveau serveur Autonomie actuellement il y a 3 situations CAE par défaut ("Réunion d'information", "Intégré", et "Sortie") et pas d'étape.

Je propose d'avoir à la place les situations CAE suivantes : 
- Candidat
- En convention
- Entrepreneur salarié
- Sortie

Et d'ajouter les étapes de parcours par défaut suivantes : 

Libellé | Nouvelle situation CAE | Type d'étape
------------ | ------------- | -------------
Diagnostique | - | Autre
Contrat CAPE | En convention | Entrée CAE
Contrat CESA | Entrepreneur salarié | Contrat de travail
Avenant contrat | - | Avenant contrat de travail
Sortie de la coopérative | Sortie | Sortie CAE

De plus je propose de affecter automatiquement la première situation CAE (dans l'ordre, par défaut "Candidat" donc) à la création des fiches Gestion Sociale ; et de faire en sorte qu'il ne puisse pas y avoir de fiches sans situation CAE.

Qu'en pensez-vous ?

**Comment by eheliot12** [comment]
ok, pour les nouveaux état et la situation CAE par défaut, ca fait un champ de moins a renseigner lors de la creation.
néanmoins attention il faut pouvoir générer facilement des stat sur les diagnostics et les reunions d'information. aujourd'hui cela se faisait sur Situation CAE

bien tester l'ajout de fiches par import csv, ca me semble etre le bon usage pour la creation de fiches en lien avec la réunion d'info collective : les gens s'inscrivent à cette réunion via un formulaire externe, la CAE collecte les infos et les injecte dans autonomie.

pour l'orthographe dans les ihm, diagnostique -> diagnostic

**Comment by eheliot12** [comment]
apres qq tests
* situation CAE semble avoir disparu pour les utilisateurs mais on le retrouve en configuration, comme une sous-couche residuelle. libelle d'etape et situation font sans doute trop doublon
* on ne peut pas gerer plusieurs etats "candidats", on a des situations cae non definies
* le bouton nouvelle entree sociale autorise la creation de compte, sans gerer l'etat ? 

*****
il faut sans doute aller un cran plus loin et fusionner plus completement situation cae dans les etapes.
* avec un type d'etape pre-entree (avec un champ date)
* remettre la creation de compte en lien avec l'etape plutot qu'avec situation cae

situation cae deviendrait l'etat courant calcule a partir des etapes

*********
le decoupage en sous-page, la creation d'entree minimaliste : tres bien
