### ISSUE TITLE
Liste des factures : erreur lors du tri sur certains champs

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#534]
Si l'on trie sur les champs "Nom de l'entreprise" ou "Date de paiement", Une erreur se produit.

Le problème 
Les join pour les tables company et Payment sont ajoutés si nécessaire dans les filtres.
Ils devraient également être ajoutés lorsque l'on trie.

**Comment by eheliot12** [comment]
pas vu de bug sur https://demo.autonomie.coop/invoices. solde ?

**Comment by tonthon** [comment]
Corrigé
