### ISSUE TITLE
Formation : Ajout d'une fiche formateur

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#552]
Epic : #457 
La fiche formateur vient étendre le modèle User afin de collecter les informations spécifiques à un formateur 

- Ajout du modèle
- Ajout des vues (Ajout/Édition/Suppression/Liste/Attacher un fichier)
- Calcul de l'Acl (liste des droits par compte)
- Api rest d'export (vers un site public par exemple)

**Comment by eheliot12** [comment]
formateur exterieur : c'est donc un formateur qui va animer une partie d'un parcours, ie une ou des sessions. il lui faut une fiche formateur. il peut être désigné comme animateur d'une session. 
il n'a pas besoin a priori d'un compte autonomie, le back office sera fait par la coopérative. pour un sous-traitant régulier, on peut imaginer qu'un compte autonomie soit ajouté. 
_quand on gérera les fournisseurs, il en fera partie_
