### ISSUE TITLE
Accompagnement - ateliers - vue entrepreneur : la colonne présence n'est pas remplie

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#566]
Depuis l'interface d'une entreprise, dans Accompagnement-Ateliers, la colonne présence n'est pas renseignée **si il n'y a qu'une personne de l'enseigne parmis les participants**.

**Comment by JocelynDelalande** [comment]
J'ai l'impression que c'est OK sur la version de dév : ![image.png](https://images.zenhubusercontent.com/5af71ced4b5806bc2bd2e214/76576e1c-a1bf-48f8-ad21-f2526eec6d82)

Non ?

**Comment by JocelynDelalande** [comment]
J'ai reproduit l'erreur, je regardais le listing en tant qu'équipe d'appui, et non en tant qu'entrepreneu·eus·e.

![image.png](https://images.zenhubusercontent.com/5af71ced4b5806bc2bd2e214/f076ae06-01de-4fad-ac44-7eda9e271ae2)
