### ISSUE TITLE
facture numero de chrono

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#577]
aujourd'hui on peut mettre un prefixe, on peut utiliser l'année qui se met a jour lors de l'exercice suivant, et le numero de chrono est annuel

en tant que comptable, je veux pouvoir un numero de chrono facture adapte aux usages de ma structure
* le numero de chrono peut être annuel ou unique
* il peut etre prefixe et suffixe par des caractères fixes et des variables. les varables identifiees sont pour l'instant
- année
- code analytique

**Comment by JocelynDelalande** [comment]
il peut également être préfixé par le numéro de mois, ex: 2018-05-XXXX

Par contre j'ai un doute sur la possibilité (légalité) d'utiliser un préfixe (variable donc) par n° de compte du plan comptable.

> 
> Numéro unique basé sur une séquence chronologique continue, sans rupture.
> 
> Exemple : facture 01, 02, 03
> 
> Il est cependant possible d'émettre des séries distinctes lorsque les conditions d'exercice de l'activité le justifient. L'entreprise peut utiliser un préfixe par année (2018-XX) ou par année et mois (2018-01-XX).
> 
> Par exemple, si celle-ci termine le mois de janvier avec une facture numérotée 25 :
> 
> Janvier : facture n°2018-01-025
> 
> Février : facture n°2018-02-026
> 
> À faire figurer sur toutes les pages de la facture

source : https://www.service-public.fr/professionnels-entreprises/vosdroits/F31808

**Comment by paul-kilya** [comment]
Pour information le format de codification des factures dans Winscop est le suivant : 
**FC[XXXX]-[AA][MM][NNN]-[ANA]**

- XXXX : Numéro incrémenté sur l'année, sur 4 chiffres
- AA : Année, sur 2 chiffres
- MM : Numéro du mois, sur 2 chiffres
- NNN : Numéro incrémenté par entrepreneur et par mois, sur 3 chiffres
- ANA : Code analytique de l'entrepreneur

A priori cette codification semble convenir à tout le monde, même si la possibilité de le personnaliser sera sûrement la bienvenue.

Il a par contre été demandé de pouvoir avoir une numérotation distincte pour les factures en transfert de charges (entre entrepreneurs).

**Comment by JocelynDelalande** [comment]
@paul-kilya merci de l'éclairage :)


Je reviens sur ce que je disais :

> Par contre j'ai un doute sur la possibilité (légalité) d'utiliser un préfixe (variable donc) par n° de compte du plan comptable.

J'ai pris quelques minutes pour creuser, les textes qui y font référence lui-même semblent rester suffisament vagues pour permettre de choisir le découpage en séqunece un peu comme on veut :

> 7° Un numéro unique basé sur une séquence chronologique et continue ; la numérotation peut être établie dans ces conditions par séries distinctes lorsque les conditions d'exercice de l'activité de l'assujetti le justifient ; l'assujetti doit faire des séries distinctes un usage conforme à leur justification initiale ;

de https://www.legifrance.gouv.fr/affichCode.do?idSectionTA=LEGISCTA000006179228&cidTexte=LEGITEXT000006069569

et 

> 3° Le numéro unique basé sur une séquence chronologique et continue établie par l'émetteur de la facture, la numérotation pouvant être établie dans ces conditions sur une ou plusieurs séries ;

de https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000033338439&dateTexte=&oldAction=rechJO&categorieLien=id&idJO=JORFCONT000033338383

**Comment by JocelynDelalande** [comment]
Je suppose que c'est important de pouvoir configurer le même schéma de numérotation que Winscop (pour faciliter les migrations sans rupture dans les séquences).

Si on veut proposer quelque-chose de paramétrable, on peut proposer les paramètres suivants:

## Champ de configuration  : format du numéro de facture

Global à la coop.

Peut contenir des caractères (préfixes, séparateurs… etc), ainsi que des variables, entre acolades.

Exemple : `FC{SEQUENCE}-{AAAA}{MM}{NNN}-{ANA}` (c'est celui de Winscop)

Variables dispo:

- `{SEQGLOBAL}` : numéro de séquence global (aucun ràz)
- `{SEQYEAR}` : numéro de séquence annuel (ràz chaque année)
- `{SEQMONTH}` : numéro de séquence mensuel (ràz chaque mois)
- `{AAAA}` : année, sur 4 digits
- `{AA}` : année, sur 2 digits
- `{MM}` : mois, sur 2 digits
- `{NNN}` : mois d'exercice de l'entrepreneur·euse (0 = premier mois d'exercice de l'entrepreneur·euse au sein de la coop).
ertir (bloquer ?) dans le logiciel le changement de format de numérotation de facture (pas anodin)

## Initialisation

Quand autonomie succède à un autre logiciel de gestion, il faut, j'imagine, pouvoir reprendre les séquences de facturation du logiciel précédent (ex: winscop). Il faut pouvoir initialiser :

- `{SEQGLOBAL}`
- `{SEQYEAR}`, pour une année donnée
- `{SEQMONTH}`, pour un mois donné et une année donnée
- `{NNN}`, pour chaque entrepreneur·euse (ou alors, peut-on s'appuyer sur le mois d'entrée dans la coop ? @paul-kilya quelle est la logique winscop ?)

## Difficultés

- En cas de migration, il faut pouvoir initialiser le `{NNN}` pour chaque entrepreneur·euse, en plus du `{SEQUENCE}`.
- le `{NNN}` est limité à 83 ans d'exercice (c'est loin et peu probable, mais pas impossible)
- bien tester, les cas de figure sont nombreux
- encadrer/avertir/bloquer : le format de numérotation ne se change pas à la légère
- migrations, pour l'existant

## Question : où stocker ces paramètres ?

Le format serait stocké en base j'imagine, comme l'est actuellement le préfixe de n° de facture.

Les valeurs d'initialisation également ? peut-on avoir une config locale à un·e utilisateur·ice ?

## Question : quelle format de numérotation par défaut ?

L'actuel tout simple ?

**Comment by JocelynDelalande** [comment]
Pour le format par défaut, on disait conserver l'existant. Or, on a (de ce que je vois 2 formats actuellement):

1. sur l'export sage, on est sur `préfixe + official_number`
2. partout ailleurs (dont les PDF), le préfixe ne semble pas être utilisé (ex: sur le PDF on a « Facture N°323 »). Soit `official_number`

D'où ma question : par défaut je garde quoi finalement ? Je serais tenté de dire le 2. On ne parle que du défaut de toutes façons (pour coller avec ce qui a déjà été envoyé aux cients en PDF).

:question: Actuellement on a des coops en prod clients qui utilisent les préfixes ?

**Comment by JocelynDelalande** [comment]
@tonthon dit:
>  le préfixe est utilisé quasi systématiquement 

Du coup il faudra choisir entre changer ce qui est passé à sage et changer ce qui est sur les PDF pour les anciennes factures.

**Comment by JocelynDelalande** [comment]
:question: Veut-on conserver la possibilité d'avoir un préfixe spécifique sur une facture ?

**Comment by eheliot12** [comment]
pour ma part, je ne vois pas de bonnes raisons de garder cette capacité à manipuler des références documentaires

**Comment by JocelynDelalande** [comment]
@tonthon un avis sur la question ?

**Comment by JocelynDelalande** [comment]
> qq tests faits : semble bien. attention on peut initialiser des numéros à des valeurs alphabetiques.

OK, je me note ça.

> en relisant mes notes, voir si on peut rajouter le champ "antenne" qui provient de la gestion sociale. c'est pour les cae multi-etablissement

Dans l'idée ça a l'air simple, il faut juste que je regarde à quoi ça correspond dans les modèles.

**Comment by JocelynDelalande** [comment]
@eheliot12 Il y a un code analytique associé aux antennes ? C'est lui que tu voudrais voir apparaître ?

**Comment by eheliot12** [comment]
pour l'instant les antennes c'est juste un champ liste (texte), rattaché a la fiche de gestion sociale

**Comment by JocelynDelalande** [comment]
> pour l'instant les antennes c'est juste un champ liste (texte), rattaché a la fiche de gestion sociale

Pour le faire apparaître dans les n° de facture, on a donc 3 possibilités:

1. utiliser l'ID en base (mais ça ne parle probablement pas aux utilisateur·ice)
2. ajouter quelque-part un champ « code analytique de l'antenne », ou quelque-chose comme ça.
3. utiliser le libellé (mais ça peut faire des numéros à rallonge, avec des espaces… etc, semble une mauvaise idée)

(sachant que le 2. demande probablement de modifier un peu le modèle de données).

Qu'en pensez-vous ?

**Comment by JocelynDelalande** [comment]
Pour faire le point, l'essentiel de ce ticket est implémenté dans autonomie. Il manque juste le fait de pouvoir faire apparaître une référence à l'antenne. Les souci étant que :

- c'est utilisé par peu de CAE
- on stocke les antennes purement comme une liste de string

Je ne retrouve pas de trace écrite sur ce qu'on avait statué au vu de ma [dernière question sur ce ticket](https://github.com/CroissanceCommune/autonomie/issues/577#issuecomment-398724614), 

J'ai souvenir que dans notre dernière discussion (téléphone, Juin je crois), le compromis acceptable était de mettre le nom de l'antenne tronqué à un certain nombre de caractères. Charge à la structure qui configure autonomie d'utiliser un nom court qui peut être intégré à un n° de facture.

Est-ce que ça vous parle ? @eheliot12 @tonthon

**Comment by eheliot12** [comment]
j'avais en tête qu'on mettait de coté pour l'instant, mais si on peut avoir qq chose modulo la troncature, ca me va aussi. la première CAE demandeuse devrait migrer que l'année prochaine.

**Comment by JocelynDelalande** [comment]
> j'avais en tête qu'on mettait de coté pour l'instant, mais si on peut avoir qq chose modulo la troncature, ca me va aussi. la première CAE demandeuse devrait migrer que l'année prochaine.

J'ai retrouvé trace dans #612 Je vaus donc considérer ce ticket comme traité, et poursuivre la discussion sur les questions d'antenne via le ticket #612
