### ISSUE TITLE
libelle ecriture comptable

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#578]
en tant que comptable je eux que le libellé des écritures soient normees suivant les usages de ma structure.

cela donne une combinaison ordonnee d'informations limitees en nombre de caractères (limite des logiciels comptables). les variables evoquees :
* chrono facture
* code analytique enseigne
* nom client
* code client

**Comment by paul-kilya** [comment]
Quelques variables supplémentaires qui peuvent être utiles : 
- Année
- Mois
- Nom de l'enseigne
- Nom du fournisseur

Et il faut pouvoir personnaliser le format par type d'écriture (ventes, achats, frais, encaissements).

**Comment by JocelynDelalande** [comment]
Quand vous parlez d'enseigne, on est d'accord qu'il s'agit d'une « activité », ou encore d'une `Company` dans les modèles autonomie ?

**Comment by JocelynDelalande** [comment]
Et ce libellé d'écriture, cela correspond bien à la colonne du même nom dans les exports CSV de compta ? Y-a-t-il d'autres endroit ou cette information apparaît ?

**Comment by eheliot12** [comment]
oui ca doit etre ca, ce sont les entreprises liées à un entrepreneur.
enseigne = marque commerciale = entreprise des entrepreneurs.
je préfère réserver entreprise à la cae ou à d'autres personnes morales, juridiques et légalement responsables
attention "activités" ca peut être des thématiques

**Comment by JocelynDelalande** [comment]
merci @eheliot12 et @tonthon  pour les réponses.

> je préfère réserver entreprise à la cae ou à d'autres personnes morales, juridiques et légalement responsables

Pour info, du coup, il y a peut-être a ré-écrire des libellés car aujourd'hui, au moins à certains endroits, on parle d'entreprise pour des enseignes.
 
![image](https://user-images.githubusercontent.com/429633/41537225-195c93fa-7308-11e8-84bd-e2f51b4af068.png)

**Comment by tonthon** [comment]
Ref #64

**Comment by JocelynDelalande** [comment]
Est-ce qu'on veut 1 template par type de contrib ou une template générale ?

**Comment by JocelynDelalande** [comment]
@eheliot12 

> cela donne une combinaison ordonnee d'informations limitees en nombre de caractères (limite des logiciels comptables)

Cette limite est fixe ou peut varier ?

**Comment by eheliot12** [comment]
cette limite dépend du logiciel compta, je crois que c'est 30 pour quadra, 35 pour sage, 25 pour ciel. donc oui c'est variable, mais c'est un paramètre qui ne change pas souvent

**Comment by JocelynDelalande** [comment]
@eheliot12 est-ce que le template doit être distinct selon le type d'écriture comptable ? (un template / « module » d'écriture) ?

**Comment by eheliot12** [comment]
je suppose qu'il faut effectivement adapter suivant l'ecriture, par exemple
* facture : on peut avoir le client
* paiement : on peut avoir la facture, la ndf de reference, la période
* note de frais : on peut avoir le mois, et en mode détaillé, un bout de description
* achat : on pourra avoir le fournisseur
on va sans doute retrouver le code analytique partout, même si c'est redondant avec sa présence dans une autre colonne. d'ailleurs, d'autres infos peuvent être redondantes. ce n'est pas une logique d'optimisation qui guide les RAF, mais plutot la logique du signifiant, c'est-à-dire qu'un champ doit contenir suffisant d'information pour etre suffisant et être signifiant pour l'utilisateur

**Comment by paul-kilya** [comment]
Oui, il faut pouvoir personnaliser le libellé par type de pièce.

Pour info voilà ceux utilisés sous Winscop : 

**VENTES** : `{NUM_FACT_SMALL} {CODE_ANA} {NOM_CLIENT}`

**ACHATS DETAILLES** : `{NUM_FACT} {NOM_FRN} {MOTIF_ACHAT}`

**ACHATS REGROUPES** : `{NUM_PIECE_JOURNAL}`

**FRAIS DETAILLES** : `{MOTIF_FRAIS} {MOIS}{AN} {NOM_ES}`

**FRAIS REGROUPES** : `{NUM_PIECE_JOURNAL}`

**ENCAISSEMENTS** : `{NUM_FACT_SMALL} {CODE_ANA} {NOM_CLIENT}`

**REMISES DE CHEQUES** : `{NUM_REMISE}`

>
> _NUM_FACT_SMALL = `{PREFIXE}{SEQYEAR}` (ex: "FC0053")_
>
> _NUM_PIECE_JOURNAL = `{CODE_JOURNAL_CPTA}-{AN}{MOIS}{SEQMONTH}-{ANA}` (ex: "ACH-1806004-250"_

**Comment by JocelynDelalande** [comment]
Actuellement, les enregistrements comptable pour la TVA reprennent le libellé du paiement associé, est-ce que c'est bien comme ça ou est-ce que ça mérite d'être configurable par template au niveau du libellé ?

**Comment by tonthon** [comment]
j'aurai tendance à dire que oui, ça offre plus de lisibilité lorsque l'on checke les écritures

**Comment by eheliot12** [comment]
idem, le libelle donne la transaction, le comptable s'y retrouve avec les comptes et ne melange pas la partie  tva du reste. donc un meme libelle convient et apporte en plus un regroupement/tri possible si les lignes  venaient a se melanger

**Comment by JocelynDelalande** [comment]
OK, donc je laisse tel quel.

**Comment by JocelynDelalande** [comment]
En relecture+tests, à vos remarques :-)

**Comment by JocelynDelalande** [comment]
Fait en Juillet via #608 (et fusionné) Sauf erreur de ma part c'est tout bon.
