### ISSUE TITLE
Paramètre de configuration devis/facture rangés dans « infos générales »

### ISSUE THREAD

**Issue by JocelynDelalande** [CroissanceCommune/autonomie#585]
## Contexte

(petit « retour utilisateur », profitant de ma fraîcheur sur l'interface d'autonomie)

Je cherche à configurer des paramètres relatifs au factures/devis (en l'occurence : préfixe des n° de facture).

Quelles étapes :

1. Je me rend dans « Configuration », puis « Module Ventes » 

## Ce qui devrait se passer

Je m'attend à trouver les paramètres concernant les devis et factures

## Ce qui se passe

Une partie de ces paramètres est en fait dans « Configuration générale » 

## Proposition d'amélioration, de solution ou de contournement

Déplacer ces paramètres dans la section « module vente ? ». 

Qu'en pensez-vous ?

**Comment by tonthon** [comment]
Fait hier :)
