### ISSUE TITLE
Problème à la duplication d'entrée statistiques 

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#609]
AndStatisticCriterion has no attribute duplicate

**Comment by sbodrero** [comment]
@tonthon tu as un exemple que je puisse reproduire le bug stp. Merci.

**Comment by sbodrero** [comment]
Euh en fait non c'est bon :-)

**Comment by sbodrero** [comment]
Petit point supplémentaire.
Lorsque qu'autonomie copie les critères (criteria) des entrées (entries) des feuilles (sheet) des statistiques (donc quand on procède à un duplicate) le "type" de chacun des critères n'est pas importé dans la table  "base_static_criterion" donc impossible de mettre à jour les tables criterion (common, date ...)
Je règle ce bug dans un premier temps qui m'amènera à régler le second 
> AndStatisticCriterion has no attribute duplicate

**Comment by tonthon** [comment]
Le type est géré automatiquement par l'orm, il n'a pas à être manipulé

**Comment by sbodrero** [comment]
> AndStatisticCriterion has no attribute duplicate
Même soucis sur la clause OR et sur les critère liste option (OptListStatisticCriterion). J'ai ajouté les propriétés "duplicate" pour chacune des classes mais il persiste un bug sur les clauses AND et OR puisque la propriété "parent_id" n'est pas mise à jour dans les critères statistiques de base (base_statistic_criterion) pour les propriétés des enfants.
