### ISSUE TITLE
Droit sur les ateliers

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#623]
Comme équipe d'appui ou formateur ou comme entrepreneur, je peux créer et gérer un atelier.
Comme équipe d'appui j'ai accès en gestion à tous les ateliers.
Comme formateur, je n'ai accès en gestion aux ateliers pour lesquels je suis le gestionnaire (créateur) ou un des animateurs.

Comme équipe d'appui ou formateur, je peux rattacher un atelier a une affaire. essentiellement formation, mais pas seulement, on peut aussi envisager la location d'espace

**Comment by JocelynDelalande** [comment]
Prérequis : #631

**Comment by JocelynDelalande** [comment]
Pour moi ce ticket va un peu au-delà des simples droits d'accès puisqu'il faut offrir un endroit dans les menus pour que tout·te·s les formateurs puissent créer un atelier… Et on ne veut pas que ça soit dans le même menu Accompagnement/Ateliers : ça serait porteur de confusion.

On s'est mis d'accord pour quelque-chose comme ça avec @eheliot12 :

![image.png](https://images.zenhubusercontent.com/5af71ced4b5806bc2bd2e214/e19b88e4-e660-42e8-bfcf-ac415ba6de3f)

**Comment by JocelynDelalande** [comment]
Pour l'instant, dans mon développement, je rattache la gestion des ateliers à des utilisateur·ice·s  qui peuvent être issues de l'équipe d'appui ou appartenant au groupe « trainers ».

Le lien entre un atelier et les utilisateurs qui ont le droit de le modifier est fait de deux manières : soit l'utilisateur est gestionnaire de l'atelier (champ « owner »), soit il est formateur dessus.

## Quid des enseignes ?

Avec ce modèle, si on a plusieurs personnes dans une même enseigne, les unes ne peuvent pas forcément voir les ateliers des autres. Si cela est problématique, il faudra songer à ajouter un lien entre activité et enseigne.

:question: est-ce à envisager ? Dès le début ou dans un second temps ?  :question:

**Comment by eheliot12** [comment]
on verra si il y a un besoindans un second temps. un entrepreneur de la meme enseigne qui ne participe pas l'atelier en tant que formateur ne voit certes pas l'atelier, mais je ne vois pas les besoins : gérer des aspects adminsitratifs pour le compte du formateur faisant l'atelier me semble peu probable.

**Comment by eheliot12** [comment]
non, notamment parce que la cae va sous-traiter ses formations a ses entrepreneurs.

**Comment by JocelynDelalande** [comment]
> non, notamment parce que la cae va sous-traiter ses formations a ses entrepreneurs.

D'accord, donc il y a bien un statut explicite à stocker pour distinguer les ateliers internes à la CAE (qui présenteront ces champs « action financée 1/2/3 ») des autres (ateliers/séances de formation pouvant être organisés par tout un chacun en tant qu'entrepreneur). Ça te semble logique @eheliot12 ?

**Comment by eheliot12** [comment]
pour moi, ce n'est pas une distinction interne/externe, c'est une info optionnelle que l'on peut utiliser ou non dans tous les cas. c'est un système de classification voir tag qui a le "mauvais gout" d’être utilisé dans les sorties pdf

on peut imaginer a terme : 
* un système de classification pour les affaires dont les formations en particuliers. ce système influence certaines informations et images éditées dans les documents.
* ce système de classification existe au travers des projets et sous-projets. il faudrait peut-être l'imposer aussi pour l'interne. ce qui revient a peu près a la CAE comme une enseigne.

**Comment by JocelynDelalande** [comment]
@eheliot12 OK,donc ce que je retiens dans un premier temps : pas d'ACL pour ajouter un champ « action financée », chacun·e peut renseigner ou non ce champ.

(réflexion connexe à #625 toujours).

**Comment by eheliot12** [comment]
oui
