### ISSUE TITLE
Inscription aux ateliers

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#624]
Comme membre de la cae, je peux m'inscrire aux ateliers ouverts ou publics.
Comme gestionnaire d'un atelier, je peux inscrire des membres de la CAE aux ateliers ouverts, publics ou fermés
Comme n'importe qui sans compte autonomie, ni fiche de donnée sociale, je peux etre inscrit a un atelier avec juste un nom, prénom, email

un atelier peut être 
* ouvert : membres de la cae peuvent s'inscrire 
* public (pour plus tard) : diffusable, et n'importe qui peut s'inscrire
* fermé : c'est le gestionnaire qui gère les invitations

en reprenant l'idée proposée #227, les dates d'atelier peuvent être vues dans deux modes, un mode proposition, un mode confirmation (à préciser)

**Comment by JocelynDelalande** [comment]
@tonthon il me semble que tu parlais d'un changement qui avait été fait ou allait être fait dans la gestion des utilisateurs afin de permettre des utilisateur·ice·s externes, est-ce que c'est fait, à faire, ou en cours ?

**Comment by tonthon** [comment]
L'epic #513 permet de suivre ce qui a été fait.
La séparation User/Login/UserDatas a été faite.
User : une personne
Login : des identifiants
UserDatas : la fiche de gestion sociale

Quelqu'un qui n'est que User n'a aucun droit dans Autonomie (il est extérieur à l'application)

La réponse est donc oui, le travail a été réalisé (en partie tout du moins)

**Comment by JocelynDelalande** [comment]
J'ai implémenté la fonctionalité, sauf ce point : 

> en reprenant l'idée proposée #227, les dates d'atelier peuvent être vues dans deux modes, un mode proposition, un mode confirmation (à préciser)

(je ne suis d'ailleurs pas bien certain de bien le comprendre)

Est-ce qu'on peut repréciser ce point dans un autre ticket ou est-ce que ça va forcément avec ?

**Comment by eheliot12** [comment]
mode proposition (mode doodle) : un meme atelier est proposé à plusieurs créneaux mais ne sera pas fait sur l'ensemble des creneaux. on cherche les meilleurs possibilités ou on se réserve le droit d'annuler les créneaux avec trop peu de monde

mode confirmé : les sessions auront bien lieu, c'est confirmé après avoir fait le point sur les inscriptions

**Comment by JocelynDelalande** [comment]
J'ai séparé l'inscription publique vers #824

**Comment by JocelynDelalande** [comment]
> mode proposition (mode doodle) : un meme atelier est proposé à plusieurs créneaux mais ne sera pas fait sur l'ensemble des creneaux. on cherche les meilleurs possibilités ou on se réserve le droit d'annuler les créneaux avec trop peu de monde
> 
> mode confirmé : les sessions auront bien lieu, c'est confirmé après avoir fait le point sur les inscriptions

OK, compris. Je met ça dans un ticket à part non ?

**Comment by eheliot12** [comment]
ok
