### ISSUE TITLE
Rendre l'action financée facultative dans les ateliers

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#625]
les 3 champs sur les financements des actions d'accompagnement doivent être rendus facultatifs

d'ailleurs un petit bilan de l'usage de cette fonction serait intéressant en préalable. j'imagine que la structure en liste hiérarchisée avait été demandée pour l'établissement de statistiques.
mais une hiérarchie plus simple est peut-etre envisageable ?

**Comment by JocelynDelalande** [comment]
@eheliot12 Quand tu dis bilan, c'est faire le tour des CAE qui l'utilisent ?

**Comment by eheliot12** [comment]
oui, au travers de qq stat que l'admin des instances pourrait nous remonter

**Comment by JocelynDelalande** [comment]
@eheliot12 juste pour être clair, qui ferait ça ? (aller chercher ces infos).

**Comment by eheliot12** [comment]
@tonthon

**Comment by eheliot12** [comment]
quand la liste est vide, génère une erreur de champ requis quand même.
quand on souhaite configurer juste cette liste, cela n'est pas possible, tous les champs sont requis dans la page de configuration des ateliers

**Comment by eheliot12** [comment]
c'est valable pour les entretiens aussi. ce qui est encore plus problématique. les entretiens légaux ne sont pas financés
d'ailleurs c'est deux listes séparés en configuration alors qu'elles sont très liées pour ne pas dire identiques

**Comment by sbodrero** [comment]
Actuellement les listes "Intitulé de l'action financée 2" et "Intitulé de l'action financée 3" sont facultatives. 
La liste "Intitulé de l'action financée 1" propose une seule valeur par défaut. J'imagine que cette valeur est renseignée dans la configuration.
Il reste quelque chose à faire sur cette issue ?

**Comment by eheliot12** [comment]
il faut s'assurer qu'il y a bien une valeur par défaut à l'installation

**Comment by sbodrero** [comment]
Très bien merci.

**Comment by eheliot12** [comment]
vide je sais pas, mais en tout cas il faut pouvoir créer un atelier si cette info n'est pas renseignée, ou si la liste n'est même pas configurée
