### ISSUE TITLE
rendez-vous : les « entreprises concernées » ne sont pas sauvegardées

### ISSUE THREAD

**Issue by JocelynDelalande** [CroissanceCommune/autonomie#634]
## Contexte
Quelles actions a-t-on effectuées ou doit-on effectuer pour que le bogue se manifeste ?

Quelles étapes :

1. Sur la vue de création ou édition de RDV, on définit une « entreprise concernée »

![image](https://user-images.githubusercontent.com/429633/42289710-7b902c24-7fc1-11e8-9289-6d49745e891f.png)

2. On sauvegarde
3. On ré-édite le RDV

## Ce qui devrait se passer

La ou les *entreprises concernées* définies précédemment apparaissent dans le formulaire.

## Ce qui se passe

Le champ *entreprises concernées* est systématiquement vide

## Proposition d'amélioration, de solution ou de contournement
Cette partie est facultative

## Environnement logiciel

commit :

>  2e1760f1 *   4.2.0a upstream/4.2.0a Merge pull request #584 from JocelynDelalande/jd-vagrant

**Comment by tonthon** [comment]
Pour moi c'est corrigé (en tout cas je ne reproduis pas le problème)
