### ISSUE TITLE
Migration des données sociales : AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#651]
## Contexte
Quelles actions a-t-on effectuées ou doit-on effectuer pour que le bogue se manifeste ?

Quelles étapes :
1. Prendre une base en version 4.1
2. Lancer la migration
3.Une erreur survient

```
None - 2018-07-12 18:23:32,083 INFO  Running upgrade 44f964dc36a2 -> 2a66d798c55d, 4.2.0a : Migrate parcours data ([alembic.runtime.migration.run_migrations:309])
...
  File "/home/user/autonomie/autonomie/autonomie/models/career_path.py", line 306, in update_user_situation_cae
    if user.situation_situation_id != situation.id:
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by paul-kilya** [comment]
J'ai ajouté des contrôles pour pas planter la migration si le cas se présente mais je ne comprend pas d'où ça peut venir et ça cache peut être un autre problème...

Quand @tonthon reviendra il faudra faire des tests plus détaillés avec la base de prod utilisée pour comprendre comment cette situation est arrivée.
 
_____
 
Sauf erreur de ma part, si je remonte le code : 

1. L'erreur implique que `get_cae_situation_from_career_path()` a renvoyé `None`.
```
user = UserDatas.query().filter(UserDatas.id==target.userdatas_id).first()
situation = user.get_cae_situation_from_career_path(None)
if user.situation_situation_id != situation.id:
```

2. Du coup c'est que la ligne suivante de la fonction a renvoyé `None` : 
```
situation = CaeSituationOption.query().filter(
                CaeSituationOption.id == last_situation_path.cae_situation_id
            ).first()
 ```

3. Ce qui voudrait dire que le `cae_situation_id` retourné avec `last_situation_path` n'est pas Null mais n'existe pas dans la table `cae_situation_option`, ce qui devrait être impossible vu les contraintes de clé étranger de la table.
```
last_situation_path = CareerPath.query(self.id).filter(
            CareerPath.start_date <= date
        ).filter(
            CareerPath.cae_situation_id != None
        ).first()
```
