### ISSUE TITLE
Statistiques : erreur à la génération des erreurs

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#687]
Il y a une erreur dans la méthode __init__ de la classe MissingDataError 
https://github.com/CroissanceCommune/autonomie/blob/master/autonomie/statistics/__init__.py#L154
il manque un .items()

**Comment by sbodrero** [comment]
@tonthon peux-tu m'indiquer comment reproduire l'erreur s'il te plaît. Merci.

**Comment by tonthon** [comment]
en instanciant la classe MissingDatasError avec des paramètres nommés (il manque juste un .items() dans la méthode __init__ )
