### ISSUE TITLE
Fiche formation : ajout de la fonctionnalité

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#689]
Dans le cadre des développements du module formation, des fiches formation vont venir peupler un catalogue.

Ces fiches formations seront associées à des entrées dans le catalogue produit afin de permettre leur insertion dans les devis/factures Autonomie.
Elles seront exportables au format json pour pouvoir être insérées dans un site public.

Spécifications (établies en collaboration avec l'équipe de coopalpha33)

Une fiche formation collecte les éléments descriptifs d’une offre de formation. Elle intègre
notamment les informations obligatoires d’après le décret qualité, et propose également quelques
champs libres permettant de s’adapter aux spécificités des différentes CAE.
Une fiche doit être composée des champs suivants : 

Intitulé
◦ Champ texte
◦ Label : Intitulé de la formation

Objectifs généraux de la formation
◦ Champ multiligne
◦ Label : Objectifs à atteindre à l'issue de la formation
◦ Description : Les objectifs doivent être obligatoirement décrit avec des verbes d'actions

Pré-requis
◦ Champ multiligne
◦ Label : Pré-requis obligatoire de la formation

Pour qui
◦ Champ multiligne
◦ Label : Pour qui?
◦ Description : Public susceptible de participer à cette formation

Durée
◦ Champ texte
◦ Label : Durée en heures et en jour(s) pour la formation
◦ Description : Durée obligatoire minimale 7 heures soit 1 jour

Contenu de la formation
◦ Champ multiligne
◦ Label :Contenu détaillé de la formation
◦ Description : trame par étapes

Moyens pédagogiques
◦ Champs multiligne
◦ Label : Les moyens pédagogiques utilisés

Moyens logistiques
◦ Champs multiligne

Label : Les moyens pédagogiques utilisésLes plus
◦ Champs multiligne
◦ Label : Quels sont les plus de cette formation ?

Évaluation
◦ Champs multiligne
◦ Label : Modalités d'évaluation de la formation
◦ Description : Par exemple : questionnaire d'évaluation, exercices-tests, questionnaire
de satisfaction, évaluation formative,...

Lieu
◦ Champs multiligne
◦ Label : Lieu de la formation
◦ Description : Villes, zones géographiques où la formation peut être mise en place

Modalité
◦ Champ multi-valué, choix parmi deux options : intra-entreprise et inter-entreprise
◦ Label : Modalité de formation

Type de formation
◦ Champ multi-valué, choix parmi les options suivantes : individuelle – groupe – petit
groupe (moins de 5 personnes) – sur mesure – à distance
◦ Libellé : Type de formation

Dates de la formation
◦ Champ texte

Tarif
◦ Champ texte
◦ Libellé : Tarif de la formation

Trois champs libres seront également ajoutés afin de satisfaire aux besoins spécifiques de
certaines CAE, ces champs libres seront multilignes et auront pour libellé « Champ libre 1 » ...

Lors de la création d'une fiche formation, une entrée sera ajoutée au catalogue produit (modèle SaleProduct).
Tarif et Intitulé seront utilisés pour peupler ce nouvel objet.

Vues à ajouter

- [ ] Catalogue formation d'une enseigne
- [ ] Ajout/Modification/Désactivation/Suppression d'une fiche formation
- [ ] Vue Formation

**Comment by sbodrero** [comment]
@tonthon peux-tu m'indiquer ou je peux trouver une démarche similaire à celle ci dans autonomie.
Ainsi je m'inspirerais de la méthode utilisée.
Merci d'avance.

**Comment by sbodrero** [comment]
@tonthon est ce que ceci est une coquille ?

> Label : Les moyens pédagogiques utilisésLes plus
◦ Champs multiligne
◦ Label : Quels sont les plus de cette formation ?

parce que juste avant on a ceci:

> Moyens pédagogiques
◦ Champs multiligne
◦ Label : Les moyens pédagogiques utilisés

**Comment by eheliot12** [comment]
oui coquille, 3 champs différents : moyens pédagogiques, vs moyens logistiques vs les plus.

les formations sont des "ouvrages", ie des produits finis. ils peuvent etre composés d'articles de base (matériel, sessions...). et ils epuvent regrouper dans des ouvrages plus importants comme des parcours.

**Comment by sbodrero** [comment]
Ça marche merci @eheliot12.

**Comment by sbodrero** [comment]
Il faudrait qu'on détermine quels sont les champs obligatoire d'un ouvrage de type formation.

**Comment by eheliot12** [comment]
tous les champs sont necessaires d'un point de vue du datadock, mais ca fait beaucoup de champs obligatoires pour le remplissage d'un formulaire.
si on avait un mode brouillon / fini, ce serait une facon d'alleger les champs obligatoires. 
on peut aussi metre peu de champ en obligatoire, et mentionner l'obligation legale d'avoir les infos

**Comment by isoph** [comment]
J’ai fait quelques simulations d’écran, avec une proposition de prévisualisation de l’avancement de la fiche. On en parle demain…
![vide](https://user-images.githubusercontent.com/1316394/46028830-df408900-c0f1-11e8-8ff3-25608065ee76.png)
![vide alternative dates](https://user-images.githubusercontent.com/1316394/46028837-e49dd380-c0f1-11e8-915f-57d83cc92893.png)
![renseignee](https://user-images.githubusercontent.com/1316394/46028842-e8315a80-c0f1-11e8-8f33-0a7e554edcfe.png)

**Comment by eheliot12** [comment]
interessant, et si je pousse le concept un poil plus loin...
et si on part de la previsualisation avec edition de chaque champ au fur et à mesure et sauvegarde a la volee apres edition. seul le champ en cours serait en mode formulaire les autres en mode visualisation.
ca donnerait quoi ? c'est une autre approche des formulaires que l'on n'a pas dans autonomie.

**Comment by isoph** [comment]
Voici la proposition sur l’écran de fiche éditable. À discuter ensemble, c’est un fonctionnement différent d’un formulaire. Mais les champs non focusés peuvent quand même être des champs de formulaire, juste avec les bordures masquées, et le bouton d’édition peut être ajouté en CSS.

**Création fiche :** 
![dynamique 1 creation fiche](https://user-images.githubusercontent.com/1316394/46298782-3afe8c80-c5a0-11e8-8bb5-59cec8292c06.png)

**Passage au champ suivant :** 
![dynamique 2 edition tab ou clic sur bouton editer](https://user-images.githubusercontent.com/1316394/46298783-3b972300-c5a0-11e8-9956-ed2fd68d5b82.png)

**Fiche partiellement remplie**
![dynamique 3 partiellement remplie](https://user-images.githubusercontent.com/1316394/46298784-3b972300-c5a0-11e8-88b9-73019e3fb5f0.png)

**Comment by eheliot12** [comment]
j'aime bien.
sur le vocabulaire, on pourrait statuer que champ requis et l'* à coté sont les champs qu'il faut renseigner pour valider un formulaire, c'est le minimum pour avoir de la cohérence dans la base.
et obligatoire serait laissé pour les champs nécessaire par reglementation, on pourrait les mettre en emphase via autre chose que l'*, soit sur la police, soit avec un autre symbole
