### ISSUE TITLE
Refonte config "Activités" / "Secteurs d'activités"

### ISSUE THREAD

**Issue by paul-kilya** [CroissanceCommune/autonomie#701]
Actuellement il existe 2 options configurables : "Typologie des métiers/secteurs d'activité" et "Domaines d'activités"

Pour les utilisateurs la distinction n'est pas claire. D'autant plus que certains menus déroulants affichent un libellé mais proposent les options de l'autre.

Il est nécessaire de revoir et de clarifier ces 2 options. L'un devrait correspondre aux secteurs d'activités au sens institutionnel (utilisés pour les statistiques) ; l'autre à la liste des activités développées par les entrepreneurs au sein de la coopérative.

Par ailleurs le paramétrage des "domaines d'activité" semble avoir disparu de l'interface de configuration en 4.2.

**Comment by paul-kilya** [comment]
Mes propositions (soumises à réflexion) : 
- renommer "Domaines d'activités" en "Secteurs d'activité" 
- renommer "Typologie des métiers/secteurs d'activité" en "Typologie des métiers/activités"
- rendre la liste des secteurs d'activité non configurable et pré-remplie

Pour les secteurs d'activité dans Winscop on a la liste suivante qui correspondait aux besoins statistiques de CPE en 2008 : 
- Agriculture
- Artisanat
- Commerce (agent commercial)
- Commerce (négoce)
- Service aux entreprises
- Service aux particuliers
- Service aux entreprises et particuliers
- Autre

On peut également envisager d'utiliser les codes NAF de l'Insee (aux moins ceux de première catégorie) : https://www.insee.fr/fr/metadonnees/nafr2/section/B?champRecherche=false

**Comment by eheliot12** [comment]
#705 et #706
