### ISSUE TITLE
Catalogue produits : stocker un compte de vente par produit

### ISSUE THREAD

**Issue by paul-kilya** [CroissanceCommune/autonomie#702]
Les comptes de vente (classe "7") sont configurés au niveau de la coopérative, en lien avec les taux de TVA.

Quand on ajoute un produit dans le catalogue on choisit la TVA associée mais pas le compte de vente. Il faudrait pouvoir le sélectionner et le stocker dans la base pour ne pas avoir à tout réaffecter à chaque facture.

**Comment by tonthon** [comment]
Cela laisse la responsabilité de la configuration des comptes produits aux entrepreneurs, ce qui peut potentiellement générer des erreurs. Serait-ce problématique ?

**Comment by paul-kilya** [comment]
Je ne pense pas. Dans Winscop les entrepreneurs font l'affectation initiale du compte produit et la coopérative contrôle et corrige si nécessaire lors de la validation.

Globalement ça a plutôt tendance à faire gagner du temps à l'équipe d'appui et ça a un côté pédagogique intéressant pour les entrepreneurs.

**Comment by tonthon** [comment]
- [ ] Mettre à jour le modèle dans le catalogue produit
- [ ] Modifier l'api rest et le frontend js de configuration du catalogue produit
- [ ] Modifier l'api rest et le frontend js de configuration des devis/factures
- [ ] Modifier les outils de duplication
- [ ] Mettre à jour les tests

**Comment by sbodrero** [comment]
Ou peut peut-on trouver les comptes ?
Est un champ optionnel ?
Peut-on rattacher plusieurs comptes à un produit ?

**Comment by eheliot12** [comment]
les comptes dependent du plan de compte de la cooperative, c'est les comptes de classe 7 du plan comptable general.
cela doit rester un champ optionnel en terme de formulaire.
il n'y a qu'un compte rattaché à un article.
sur un ouvrage aussi je pense, mais peut-etre à discuter

**Comment by paul-kilya** [comment]
Les comptes produits sont configurés par la coopérative en lien avec un taux de TVA.

Voir dans la configuration du module de ventes : "Configuration comptable des produits et TVA collectés"

**Comment by sbodrero** [comment]
Donc on affecte automatiquement en base un champ compteTVA (VATAccount) lorsque l'utilisateur crée un produit si ce compte sélectionné est configuré ?
Il n'y a pas d'action de sélection de compte dans la fiche produit ?

**Comment by eheliot12** [comment]
on doit affecter un code tva  et un compte produit associé possible dans la fiche produit.
dans autonomie on commence par les codes tva et on y associe des comptes produits

**Comment by paul-kilya** [comment]
Dans la config on a un ou plusieurs comptes produits attachés aux taux de TVA.

Dans la fiche produit il faudrait pouvoir sélectionner le compte produit dans un menu déroulant selon la TVA sélectionnée. Exactement comme c'est fait lorsqu'on ajoute une prestation libre dans une facture.

En base ça implique que dans la table `sale_product`, en plus de la valeur du taux de TVA, il faut stocker un lien vers la table `product` (comme pour la table `task_line`).

**Comment by eheliot12** [comment]
test

**Comment by sbodrero** [comment]
Ok c'est compris merci.

**Comment by sbodrero** [comment]
Fait et mergé sur master
