### ISSUE TITLE
Devis : Affichage problématique du compte de vente

### ISSUE THREAD

**Issue by paul-kilya** [CroissanceCommune/autonomie#703]
Dans les devis quand on ajoute une prestation libre on choisit la TVA mais pas le compte de vente, ensuite dans la fiche du devis il y a une colonne "Produit" qui affiche automatiquement le premier compte de vente associé à la TVA.

Soit il faut permettre de choisir le compte dès l'ajout de la prestation, soit il ne faut pas l'afficher dans la fiche du devis.

**Comment by tonthon** [comment]
Problème à régler au niveau du frontend js ainsi qu'au niveau de l'api rest 

- [ ] permettre la configuration des produits par l'équipe d'appui
- [ ] ne pas afficher le produit dans l'interface de l'entrepreneur

**Comment by eheliot12** [comment]
j'opterai pour le fonctionnement le plus large ie la meme chose que sur les factures. même si ce n'est pas le plus efficient : il faut refaire la verif pour la facture, donc autant la faire qu'une seule fois.
