### ISSUE TITLE
Civilités client

### ISSUE THREAD

**Issue by paul-kilya** [CroissanceCommune/autonomie#707]
Il existe aujourd'hui 3 choix pour la civilité des clients : Monsieur, Madame, Monsieur et Madame

Pour permettre de gérer tous les cas de figure il faudrait pouvoir renseigner : 
- Monsieur
- Madame
- Monsieur et Madame
- Monsieur ou Madame
- Monsieur et Monsieur
- Monsieur ou Monsieur
- Madame et Madame
- Madame ou Madame

C'est en tous cas ce qui a été demandé par les utilisateurs Winscop. Sur certaines factures (notamment dans le bâtiment) ça peut être très important.

**Comment by sbodrero** [comment]
Avec autant d'options il me semble que maintenant une liste serait plus adaptée

![fireshot capture 271 - liste des clients - http___0 0 0 0_8080_company_18_customers](https://user-images.githubusercontent.com/2083775/47145176-6afc9e00-d2c9-11e8-8817-a45e1277c10d.png)

**Comment by paul-kilya** [comment]
Oui je suis d'accord, une liste sera bien plus adaptée

**Comment by eheliot12** [comment]
une liste c'est 2 clics, c'est donc 1 clic de trop dans 95% des cas, le "et" le "ou", ne me semblent pas justifiés. c'est utiliser par des fournisseurs notamment banque pour enquiquiner leurs clients sur les pouvoirs donnés.
est ce qu'on peut avoir des cases à cocher plutot que des cases radio : Madame, Monsieur, Mesdames, Messieurs, et autonomie ferait la concaténation si besoin avec des virgules

**Comment by sbodrero** [comment]
oui rien d'impossible je pars sur les cases à cocher ?
D'ailleurs qu'elle est la différence entre 'et' et 'ou' ?

**Comment by paul-kilya** [comment]
Dans le bâtiment notamment les "et"/"ou" peuvent être importants, c'est pour ça qu'on me les a fait ajouter dans Winscop.

Si j'ai bien compris sur des gros chantiers ou achats en cas de séparation le bien ne sera pas traité de la même façon si c'est "et" ou "ou" sur la facture. A vérifier éventuellement avec les CAE bâtiment.

Autant je suis pour éviter un clic inutile si c'est facilement faisable, autant là ça me semble plus souple d'utiliser une liste.

**Comment by sbodrero** [comment]
Je craint que la case à cocher ne soit pas très facilement compréhensible et ça supprime la nuance du 'et' et 'ou'

**Comment by eheliot12** [comment]
question posée sur tilt

**Comment by sbodrero** [comment]
On attend un retour sur cette question ?

**Comment by eheliot12** [comment]
oui

**Comment by sbodrero** [comment]
Pas de retour ?

**Comment by eheliot12** [comment]
un retour, qui va dans le sens de la liste, mais qui ne definit pas le contenu de la liste et ne justifie pas reellement le besoin.
si on doit statuer maintenant, on partira sur le format liste. meme si je ne suis pas convaincu du tout du besoin

**Comment by eheliot12** [comment]
quitte a avoir une liste, autant qu'elle soit configurable par un admin.
par défaut à l'installation, on aurait madame, monsieur et c'est tout

**Comment by sbodrero** [comment]
Est ce qu'on fait ça en 2 temps ?

1. Mise en place de la liste
2. Ajout d'une option dans la partie "Configuration générale" (par exemple) pour personnaliser la liste des civilités des clients

**Comment by eheliot12** [comment]
ce qui est le plus pratique pour toi, et le plus rapide

**Comment by sbodrero** [comment]
Le plus rapide c'est de mettre en place la liste puis créer une issue
"amélioration" pour la suite.
Après il faut voir comment les utilisateurs vont accueillir cette liste.


Sébastien Bodrero est membre de Kanopé,
   SCOP Sarl à capital variable - RCS AUCH 429 228 018
SEBASTIEN BODRERO
Full Stack & Mobile Senior Developer
ReactJS, React Native & Java addicted
m: 0649676333  e: bodrero.sebastien@gmail.com
<https://twitter.com/sbodrero>
<https://www.linkedin.com/in/s%C3%A9bastien-bodrero-78256357/>
