### ISSUE TITLE
Annuaire : Ajout un filtre pour l'équipe d'appui

### ISSUE THREAD

**Issue by paul-kilya** [CroissanceCommune/autonomie#711]
Il n'est pas possible actuellement d'afficher la liste des membres de l'équipe d'appui.

Il faudrait ajouter un filtre sur l'annuaire pour le rôle des utilisateurs.

**Comment by sbodrero** [comment]
Est ce que ce filtre est à destination des utilisateurs de type entrepreneur ou tous les utilisateurs ?

**Comment by sbodrero** [comment]
Une case à cocher devrait faire l'affaire :
"Membre de l'équipe d'appui" ?

**Comment by paul-kilya** [comment]
Non, pas besoin de toucher au modèle. L'idée est juste d'ajouter la possibilité de filtrer sur le rôle (table `user_groups`) sur la page d'annuaire des utilisateurs (en plus des types d'activités et des comptes actifs ou pas).

**Comment by eheliot12** [comment]
case à cocher : ok, 

reflexion a mener pour le moment  ou les critères demandés vont deobrder de la page

**Comment by eheliot12** [comment]
si c'est deja developpe sous forme de liste avec les differents groupes, ca me va aussi, comme c'est pas d'un usage frequent les 2 clics ne me genent pas plus que ca.

**Comment by sbodrero** [comment]
Très bien merci @eheliot12 ça part en PR

**Comment by paul-kilya** [comment]
Fait avec la PR #752
