### ISSUE TITLE
Parcours : Erreur 500 lors de la suppression d'une fiche Gestion Sociale

### ISSUE THREAD

**Issue by paul-kilya** [CroissanceCommune/autonomie#713]
S'il y a des étapes de parcours sur une fiche Gestion Sociale on obtient une erreur 500 lors de la suppression de la fiche à cause des contraintes de clé étrangère.

`IntegrityError: (_mysql_exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`autonomie`.`career_path`, CONSTRAINT `fk_career_path_userdatas_id` FOREIGN KEY (`userdatas_id`) REFERENCES `user_datas` (`id`))') [SQL: u'DELETE FROM user_datas WHERE user_datas.id = %s'] [parameters: (3452L,)]`

Il faut ajouter le traitement de suppression du parcours.

**Comment by tonthon** [comment]
Il faut configurer les ForeignKey ou au niveau de la relationship pour que la suppression se fasse en "cascade". https://docs.sqlalchemy.org/en/latest/orm/cascades.html

Ex : 
https://github.com/CroissanceCommune/autonomie/blob/master/autonomie/models/accounting/operations.py#L133

**Comment by paul-kilya** [comment]
La suppression en cascade va être ajoutée au modèle.

Pour les bases existantes il faut exécuter les requêtes suivantes : 
```
ALTER TABLE `career_path` DROP FOREIGN KEY `fk_career_path_userdatas_id`;
ALTER TABLE `career_path` ADD CONSTRAINT `fk_career_path_userdatas_id` FOREIGN KEY (`userdatas_id`) REFERENCES `user_datas`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
```
