### ISSUE TITLE
Accompagnement : Lister les réunions d'information collective

### ISSUE THREAD

**Issue by paul-kilya** [CroissanceCommune/autonomie#715]
En tant que membre de l'équipe d'appui je veux pouvoir visualiser facilement la liste des réunions d'info coll.

Pour cela il faut pouvoir identifier un atelier comme étant une réunion d'info coll, via par exemple une case à cocher lors de la saisie.

**Comment by eheliot12** [comment]
usage : dans la fiche de données sociale, en tant que membre de l'équipe d'appui, je veux pouvoir renseigner la date d'infocoll sans avoir une tierce liste sous un autre outil. idéalement je ne peux sélectionner que des dates d'infocoll.
attention : une infocoll, c'est aussi un lieu

**Comment by eheliot12** [comment]
plutot qu'une case à cocher cela peut être une liste de typage, pour avoir plus de souplesse, et faire définir la liste par la CAE

**Comment by paul-kilya** [comment]
Si on propose un typage des ateliers (ce qui peut être une bonne idée) il faudra quand même ajouter la case à cocher sur la configuration sinon on se pourra pas plus identifier les infos coll. Ou alors il faut avoir un type par défaut non modifiable.

**Comment by paul-kilya** [comment]
Après en avoir parlé avec Gaston et Sébastien on pense qu'il n'est pas nécessaire de modifier le modèle des ateliers. La date d'info coll est déjà présente sur la fiche sociale (ça demande une petite double saisie du coup mais bon) donc pour les stats on utilisera celle là.

Pour ce qui est de pouvoir lister directement les infos colls il nous semble qu'ajouter un filtre dans la liste sur le premier niveau d'action financée est suffisant, ainsi il suffira que les CAE configurent un titre d'atelier correspondant à l'info coll (c'est déjà ce qu'ont fait les CAE utilisatrices) pour pouvoir les retrouver facilement.

Par contre à mon avis il y a un problème de libellé là aussi. Dans la configuration ça s'appelle "Titres" et "Sous-titres", et dans les fiches atelier on parle de "Intitulés de l'action financée". Je pense qu'il faudrait avoir la même chose dans les 2 cas, et peut être qu'on peut trouver quelque chose de plus parlant et plus général (en expliquant que ça peut correspondre au nom de l'action financée pour le FSE en description par exemple).
