### ISSUE TITLE
droit pour renseigner compte produit pour facture

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#718]
la fonction "configurer les comptes produits" doit être disponible sur devis, facture pour les entrepreneurs ayant les droits de valider respectivement devis ou facture

**Comment by paul-kilya** [comment]
A discuter mais je ne vois pas bien l'intérêt de ne pas permettre aux entrepreneurs de les configurer.

Dans tous les cas la coopérative doit les vérifier puisque ça part en compta, et d'un point de vue pédagogique le plus tôt les entrepreneurs prennent l'habitude d'associer une vente à un compte produit mieux c'est (d'après les coopératives avec lesquelles j'en ai discuté).

En tous cas il me semble qu'il faut pouvoir permettre à un entrepreneur de les configurer même s'il ne peut pas encore valider ses devis et/ou factures.
