### ISSUE TITLE
modification projet : les types de projet  conventions formation et chantiers disparaissent

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#721]
sur 4.2.0a0
a la creation d'un projet, on a bien chantier, et convention avec projet classique, special

lors de la modification d'un projet de formation, un message d'erreur apparait apres la modification d'une info : le type de projet est requis sans etre selectionne, il ne reste que simple ou special

**Comment by tonthon** [comment]
À la modification d'un projet, on ne peut pas changer son type, on peut cependant changer les types d'affaires que l'on peut créer dedans (hormis le type d'affaire associé au type de projet)
Ainsi dans un projet formation, on peut choisir de permettre la création d'affaire qui ne sont pas liées au formation comme des "Affaires simples"

**Comment by tonthon** [comment]
![capture du 2018-10-08 19-48-23](https://user-images.githubusercontent.com/592723/46625157-2471ab80-cb33-11e8-976a-05ccdace343c.png)

**Comment by tonthon** [comment]
![capture du 2018-10-23 12-40-03](https://user-images.githubusercontent.com/592723/47355112-cdd2a880-d6c0-11e8-95f6-b1db45ded535.png)
