### ISSUE TITLE
Ajout de notes complémentaire sur les factures

### ISSUE THREAD

**Issue by paul-kilya** [CroissanceCommune/autonomie#737]
Sur les devis il est possible d'ajouter des notes complémentaires qui s'affichent à la fin du document mais sur les factures actuellement ce n'est pas possible.

Il faut ajouter cette possibilité sur les factures.

**Comment by paul-kilya** [comment]
Techniquement les notes complémentaires des devis sont stockées dans le champs `exclusions` (???) du modèle `estimation`.

On peut ajouter le même champs dans le modèle `invoice` mais le plus propre serait de le déplacer vers le modèle `task` dont héritent les 2 autres.

**Comment by tonthon** [comment]
(au passage, on pourrait renommer le champ et le nommer ... notes
