### ISSUE TITLE
Dans les devis et factures l'éditeur de texte tinymce ne fonctionne plus.

### ISSUE THREAD

**Issue by sbodrero** [CroissanceCommune/autonomie#741]

**Comment by paul-kilya** [comment]
Sur mon serveur de test le problème est apparue suite à la mise à jour du code depuis le master après avoir lancé le `setup.py`.

Dans la console javascript j'ai une erreur `uncaught exception: module [tinymce.core.ui.Api] returned undefined`, sûrement liée au warning que j'ai juste avant : 
```
Erreur dans les liens source : request failed with status 404
URL de la ressource : http://autonomie.kilya.net/fanstatic/fanstatic/js/build/task.js
URL du lien source : task.js.map
```

**Comment by paul-kilya** [comment]
Bon au final le warning n'a pas de lien, même avec le fichier `task.js.map` dispo l'erreur persiste

**Comment by sbodrero** [comment]
Erreur fixée par les derniers merges.
Je déplace dans la colonne OK
