### ISSUE TITLE
Gestion sociale : intégrer le parcours dans la fusion documentaire

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#749]
Dans la fusion documentaire de la gestion sociale, les entrées de gestion sociale sont converties en des structures de données qui reflètent des variables utilisables dans les modèles de document odt.
Exemple : 
la variable py3o.coordonnees_lastname sera automatiquement remplacée par le nom de famille du porteur de projet lors de la fusion.

Il faut proposer ici un complément qui permettra l'intégration des données de parcours.

**Comment by tonthon** [comment]
Fournir des données par type d'étape de parcours
```
py3o.ContratCAPE.last.start_date (Date de départ de la dernière convention CAPE du porteur de projet)
py3o.ContratCAPE.fist.start_date (Date de départ de la première convention CAPE du porteur de projet)
```

**Comment by paul-kilya** [comment]
D'expérience pour mieux répondre aux différentes organisations et évolutions contractuelles potentielles il vaut mieux faire des critères de fusion doc (et stats) sur les situations CAE que sur les étapes en elle-même. C'est à dire que plutôt que de faire un critère qui récupère la dernière date de parcours d'une étape "Contrat CAPE", on en fait un qui récupère la dernière date de parcours d'une étape qui a changé la situation CAE de l'entrepreneur à "En convention" (pareil pour les contrats et les sorties).

La plupart du temps ça revient au même pour les utilisateurs, mais pour ceux qui utilisent encore les conventions d'accompagnement plutôt que les CAPE ou si un jour les CAPE sont remplacés par autre chose la fusion marche quand même. Ça permet aussi aux CAE de créer plusieurs étapes qui font la même chose mais avec une distinction.

**Comment by tonthon** [comment]
Pour moi c'est ok, on peut désormais inclure les éléments dans les documents fusionnés

**Comment by tonthon** [comment]
Les clés sont de la forme : 
py3o.<nom de l'étape sans accent>.last.start_date
Soit : 
```
py3o.ContratCAPE.last.start_date
```
