### ISSUE TITLE
Erreur 500 sur /trainings/ : « unknown column business.status. »

### ISSUE THREAD

**Issue by JocelynDelalande** [CroissanceCommune/autonomie#757]
## Contexte
Quelles actions a-t-on effectuées ou doit-on effectuer pour que le bogue se manifeste ?

Quelles étapes :

1. Se rendre sur /trainings/ en tant qu'admin

## Ce qui devrait se passer

Afficher la liste des actions de formation

## Ce qui se passe

Erreur 500 : 

![image](https://user-images.githubusercontent.com/429633/47229001-e98b3580-d3c6-11e8-8ba9-86405d108492.png)

## Environnement logiciel

b63e613b3e0257ba0d7d7b4577882eed05023153

**Comment by JocelynDelalande** [comment]
@tonthon je te l'assigne car ça concerne cette vue que tu as ajouté dans dd172bd6955cd647ccb3627607086751391b03fb

**Comment by JocelynDelalande** [comment]
NB: @paul-kilya a été en mesure de reproduire le bug

**Comment by tonthon** [comment]
C'est un problème de migration, vos bases n'ont pas la structure désirée.

**Comment by paul-kilya** [comment]
Pour mettre à jour à la main : 

`ALTER TABLE business ADD status VARCHAR(8) NULL DEFAULT 'danger' AFTER closed;`

**Comment by JocelynDelalande** [comment]
@tonthon Est-ce que ça ne veut pas dire qu'il manque un script de migration ? (du coup je ne suis toujours pas certain d'avoir compris notre logique de ce qui doit faire l'objet d'une migration ou non).

@paul-kilya merci pour l'astuce.
