### ISSUE TITLE
rendre les images des entetes et pieds facultatives dans les ateliers

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#759]

**Comment by sbodrero** [comment]
On est bien sur la partie "Configuration du module Atelier" ?

**Comment by eheliot12** [comment]
oui https://demo.autonomie.coop/admin/workshop

si je remplis juste certains champs de la config, ca doit passer. et pas me mettre une erreur

ensuite dans l'usage, dans les ateliers, faut qu'on puisse imprimer. 

piste pour faire rapide : par défaut autonomie charge un fichier, de bannière vide, un png de la bonne taille transparent. 

en refaisant un petit test : il y a d'ailleurs un ecart entre demo et la 4.2.0a0. sur demo, pas d'erreur, soit un fichier a ete mis en cahce soit ca ne genere pas l'erreur

**Comment by tonthon** [comment]
On peut facilement rendre l'image facultative, ça n'empêchera pas la génération de pdf
