### ISSUE TITLE
facture : filtrer sur identifiant ne marche plus

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#776]
en dev 4.2.0a0

avec un identifiant complexe

**Comment by sbodrero** [comment]
@eheliot12 tu as un exemple d'identifiant complexe s'il te plaît.

**Comment by eheliot12** [comment]
facture d'identifiant FC2863-1810001-3AREN, 
si je filtre sur 3aren, je n'obtiens rien
si je filtre sur FC2863-1810001-3AREN je n'obtiens rien non plus

**Comment by sbodrero** [comment]
Ok merci je part la dessus merci @eheliot12

**Comment by sbodrero** [comment]
De mon côté le filtre sur l'identifiant entier fonctionne (FC2863-1810001-3AREN) mais par sur une valeur partielle de ce dernier.

**Comment by eheliot12** [comment]
j'ai refait : ok mais faut pas un espace de trop.
ce n'est peut-etre plus un bug en tant que tel, mais bon il faut que cela fonctionne sur un identifiant partiel, sinon c'est inutilisable

**Comment by sbodrero** [comment]
Oui c'est clair je suis entrain de mettre en place la recherche partielle.

**Comment by paul-kilya** [comment]
Et il faut aussi retirer les espaces ou tabulations avant et après la recherche s'il y en a
