### ISSUE TITLE
devis/facture : les legendes des couleurs ont disparu

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#777]
dev 4.2.0a0

**Comment by sbodrero** [comment]
On parle bien de cette légende ?
![fireshot capture 277 - factures de l entreprise renard et_ - http___0 0 0 0_8080_company_18_invoices](https://user-images.githubusercontent.com/2083775/47795441-dcedd200-dd22-11e8-8604-1cc69b19c812.png)

**Comment by eheliot12** [comment]
oui, ca semble donc bon

**Comment by sbodrero** [comment]
Oui de ton côté aussi ?

**Comment by eheliot12** [comment]
oui je viens de verifier que la version actuelle du serveur de migration contenait bien cette legende repliée

**Comment by sbodrero** [comment]
Ok je ferle l'issue alors.
