### ISSUE TITLE
Erreur à la migration lorsque l'on a plusieurs produits associés à une même TVA

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#793]
Erreur dans :
 autonomie/autonomie/alembic/versions/4_2_0a0_added_product_id_to_sale_product_table_4f011ed2a459.py 

```
(1054, "Unknown column 'None' in 'field list'") [SQL: 'UPDATE sale_product SET product_id=None WHERE id=359']
```
Il faudrait soit tester la présence d'une valeur None, soit utiliser l'ORM qui saura la gérer.

**Comment by sbodrero** [comment]
La valeur None vient du fait que tu n'as pas de compte produit pour ce taux de tva ?

**Comment by tonthon** [comment]
non plusieurs

**Comment by tonthon** [comment]
il y a juste un test à rajouter

**Comment by tonthon** [comment]
ou utiliser l'orm, le raw sql c'est source d'erreur et potentiellement de grave erreur (si il y a des quotes dans les variables par exemple)

**Comment by sbodrero** [comment]
ok je regarde en passant via l'orm

**Comment by sbodrero** [comment]
En fait j'avais oublié de faire un test None value si le taux de tva est null 👎
