### ISSUE TITLE
catalogue produit : liste produits bouton ajouter

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#796]
4.2.0a0
ce bouton ne fonctionne pas,
pour liste ouvrage et formation, ca marche par contre

de meme le bouton modifier sur un produit ne marche pas
mais marche sur les ouvrages et formations

**Comment by sbodrero** [comment]
Oui c'est corrigé @tonthon a géré les pull request

**Comment by eheliot12** [comment]
et dans le devis quand on ajoute un element depuis le catalogue, le bouton "editer comme un nouvel element" c'est pareil ?

**Comment by sbodrero** [comment]
Je ne peux pas tester maintenant car j'ai un soucis de migration mais je dirais que oui puisqu'il s'agit du script qui va chercher les compte produits. Tu as déjà essayé de vider le cache j'imagine ?

**Comment by eheliot12** [comment]
oui

**Comment by sbodrero** [comment]
Ok je viens de tester et non "editer comme un nouvel element" ne correspond pas au même bug.
Il est en rapport avec l'issue #751

**Comment by sbodrero** [comment]
Par contre je te confirme que le bouton ajout de produit dans le catalogue fonctionne sur la branche principale.
