### ISSUE TITLE
Migration cassée : "Unknown column 'task.notes' in 'field list'

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#804]
Migration : l'ajout du champ "notes" aux task devraient être déplacé dans https://github.com/CroissanceCommune/autonomie/blob/master/autonomie/alembic/versions/4_2_0_add_project_type_44f964dc36a2.py
ou une table simplifiée devraient être utilisée dans ce script

**Comment by paul-kilya** [comment]
Fix and merge in  #833
