### ISSUE TITLE
Trier les factures/avoir par date

### ISSUE THREAD

**Issue by GuillaumeAmat** [CroissanceCommune/autonomie#82]
Lorsqu'on visite un projet, la page est divisée en deux sections : devis, factures/avoirs
Tous les documents sont triés par date excepté si on a des factures **et** des avoirs.

Dans ce cas, les avoirs sont placés en-dessous des factures et l'ordre chronologiques n'est plus respecté.

**Comment by eheliot12** [comment]
semble dispo
