### ISSUE TITLE
Api rest d'édition de devis facture : empêcher l'édition de l'identifiant²

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#822]
Version 4.1.0
Cas observé sur des instances en production 

Depuis le formulaire, à la validation, la requête qui est lancée pour s'assurer de la sauvegarde du "common model" du formulaire, contient des données incohérentes. Elles incluent des données (notamment l'identifiant) provenant des prestations. 

L'erreur suivante est alors soulevée
```
IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`autonomie`.`task`, CONSTRAINT `fk_task_id` FOREIGN KEY (`id`) REFERENCES `node` (`id`))') [SQL: u'UPDATE node SET id=%s, updated_at=%s WHERE node.id = %s'] [parameters: (55293, datetime.datetime(2018, 11, 5, 21, 58, 55, 745841), 32343L)]
```

- Ce problème ne devrait pas se produire (je n'ai pas réussi à la reproduire)
- Par mesure de précaution : l'identifiant ne devrait pas être inclu dans les données à modifier (il devrait être exclu du schéma d'édition).

**Comment by sbodrero** [comment]
l'identifiant à exclure correspond à celui du Node (common model) ?

**Comment by tonthon** [comment]
Non, c'est le champ id de manière générale.
La modification doit être apportée dans le views/task/rest_api.py ou directement dans le forms/task/task/py

**Comment by tonthon** [comment]
je ne pense d'ailleurs pas que ta modif impacte le schéma de formulaire

**Comment by tonthon** [comment]
Petite explication : 
Si j'édite un devis, j'ai une instance d'Estimation.
Estimation.id correspond aux colonnes Node.id, Task.id, Estimation.id (sur les deux dernières tables, ce sont des ForeignKey).
Donc si j'édite Estimation.id, je modifie l'ensemble de ces ids.

Pour simplifier, le schéma de formulaire sert à s'assurer du contenu d'un dictionnaire de valeurs {<attribut du modèle>: <nouvelle valeur>}. Le dictionnaire résultant est appliqué sur l'instance du modèle.

donc si le dictionnaire contient {id: <un nouvel id>}, potentiellement, le code de la vue (au travers de colanderalchemy), va faire un setattr(<mon instance d'Estimation>, 'id', <nouvel id>).

C'est cette dernière éxécution qu'on veut éviter. Pour cela il faut s'assurer que l'id ne soit pas dans le formulaire.

Donc soit on déplace le code que tu as mis dans les objets Estimaiton Invoice et CancelInvoice
soit on modifie le code de get_add_edit_task_schema, soit on modifie l'appel qui est fait à cette fonction.
