### ISSUE TITLE
devis : injection depuis catalogue produit

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#839]
4.1
quand on injecte un produit du catalogue, on peut insérer ou éditer. les fonctionnements sont différents. insérer fonctionne bien, mais éditer génère des incohérences
* le champ description contient le nom du produit et pas sa description
* unité est mise par défaut sur la première valeur de la liste et pas l'unité du catalogue

**Comment by paul-kilya** [comment]
Constaté en 4.2

En lien avec #735

**Comment by eheliot12** [comment]
@paul-kilya 
test 4.2 : ok mais c'est le taux de tva qui saute maintenant en mode éditer, le taux de tva par defaut prend la place du taux defini

**Comment by paul-kilya** [comment]
@eheliot12 Je ne parviens pas à reproduire le problème avec la TVA. Tu peux me donner un exemple ?

**Comment by eheliot12** [comment]
http://autonomie-preprod.majerti.fr/estimations/63428
le bug se manifeste sur le compte produit, pas sur la tva,

**Comment by paul-kilya** [comment]
Ben même sur le compte produit je ne vois pas de bug... :/

**Comment by eheliot12** [comment]
les deux produits qui sont les memes ont ete injecte differemment et ils ont un compte produit different

![image](https://user-images.githubusercontent.com/33490126/48759109-6fd6b800-eca2-11e8-95cf-b9129ea340e8.png)

**Comment by paul-kilya** [comment]
Ok, en fait le problème n'est pas l'édition du produit du catalogue mais l'envoi d'une saisie libre.
Je regarde ça.
