### ISSUE TITLE
test4.2 / reactivation d'une enseigne ne fonctionne plus

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#870]
renvoie sur la page enseigne mais sans la reactiver
la desactivation fonctionne
l'activation/desactivation des users fonctionne

**Comment by eheliot12** [comment]
la réactivation marche depuis la fiche entreprise mais pas depuis la page des entreprises http://autonomie-preprod.majerti.fr/users/222/companies

lors d'une desactivation via la page de l'enseigne, le compte utilisateur a été desactive dans la meme action

**Comment by JocelynDelalande** [comment]
Je confirme et j'ajoute que sur `/companies/195`, le bouton « ré-activer » pointe vers la mauvaise URL.
