### ISSUE TITLE
test 4.2 / qq internals erreurs

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#872]
sur une fiche de gestion sociale, creer une fiche formateur
sur menu principal accompagnement atelier / en mode admin. ok en mode entrepreneur

**Comment by eheliot12** [comment]
http://autonomie-preprod.majerti.fr/company/138/commercial

**Comment by JocelynDelalande** [comment]
@eheliot12 ça nous fait 3 cas :

> sur une fiche de gestion sociale, creer une fiche formateur

Tu peux détailler avec des URL qui échouent et utilisateur que tu ulitise ? Je n'arrive pas à produire de crash

>  sur menu principal accompagnement atelier / en mode admin. ok en mode entrepreneur

On parle de l'URL https://autonomie-preprod.majerti.fr/workshops

Reproduit sur démo mais pas en local. @tonthon tu aurais les logs ou bien un dump de l'état actuel de ta base autonomie-preprod que je bosse ça en local ?

> 

> http://autonomie-preprod.majerti.fr/company/138/commercial

ok reproduit sur démo et en local.

**Comment by JocelynDelalande** [comment]
La 3e erreur est corrigées dans #900. En attente d'infos poru les autres.

**Comment by eheliot12** [comment]
cas1 : http://autonomie-preprod.majerti.fr/users/381/trainerdatas/add par exemple, semble etre sur des fiches de non integres

cas 2 oui http://autonomie-preprod.majerti.fr/workshops

**Comment by eheliot12** [comment]
il y a aussi http://autonomie-preprod.majerti.fr/companies/138/accounting/treasury_measure_grids

**Comment by JocelynDelalande** [comment]
Merci pour les détails.

> cas1 : http://autonomie-preprod.majerti.fr/users/381/trainerdatas/add par exemple, semble etre sur des fiches de non integres

OK, reproduit en local.

> il y a aussi http://autonomie-preprod.majerti.fr/companies/138/accounting/treasury_measure_grids

OK, reproduit en local.

**Comment by JocelynDelalande** [comment]
Cas 1, 3 et 4 corrigés dans #900 

Il me faut des infos (dump ou logs de l'instante) de la part de @tonthon pour gérer le cas 2.

**Comment by JocelynDelalande** [comment]
Le cas 2 était lié à l'ancien champ Workshop.leaders qui a été supprimé depuis (PR #726 ). Plus de champ, plus de problème :-).

L'ensemble des corrections pour ces erreurs est donc contenu dans #900 qui est prête pour fusion.
