### ISSUE TITLE
test 4.2 / ajout des droits specifiques aux affaires

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#874]
il semble que la liste des droits soit incomplete et ne propose pas de droit pour les affaires

![image](https://user-images.githubusercontent.com/33490126/48546249-29f7a980-e8c8-11e8-8070-b6b12656e0a5.png)

**Comment by tonthon** [comment]
Corrigé : cela venait de l'instance de test, la commande syncdb n'avait j'amais été lancée
