### ISSUE TITLE
fiche client : nom du contact pour personne morale à rendre non obligatoire

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#878]

**Comment by paul-kilya** [comment]
Il me semble que l'adresse ne devrait pas être obligatoire non plus. Il est fréquent qu'elle soit ajoutée dans un second temps.

En fait pour moi seul le nom (de famille pour les personnes physique, de structure pour les personnes morales) devrait être obligatoire.

@eheliot12 Tu en penses quoi ?

**Comment by eheliot12** [comment]
oui, cf. #924 pour discussion générale
pour l'adresse, elle est nécessaire pour la création de devis, et facture. mais comme on peut les renseigner dans chaque document, elle ne devrait effectivement pas être obligatoire dans le formulaire

**Comment by tonthon** [comment]
Pour le nom du contact dans le cas des personnes morales, il a été indiqué comme obligatoire suite à la demande des utilisateurs.
Cela permet notamment de savoir à qui s'adresser en cas d'impayé et éventuellement de vérifier que cette personne a bien la possibilité de passer des commandes au nom de la structure.

**Comment by eheliot12** [comment]
je comprends mais on a des demandes inverses aussi
