### ISSUE TITLE
test 4.2 / notes de depense export libelle ecriture

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#881]
{expense.description} genere une erreur 500

-> piste : on groupe les depenses donc pas forcement facile de choisir une {expense.description}

**Comment by eheliot12** [comment]
#556 peut-etre necessaire

**Comment by JocelynDelalande** [comment]
> -> piste : on groupe les depenses donc pas forcement facile de choisir une {expense.description}

Tout à fait. une Note de dépense n'a pas de description. Deux approches possible à ce stade (sans passer par #556 )

A. enlever de la doc `expense.description`
B. laisser `expense.description` et l'implémenter sous forme d'une concaténation des description de toutes les lignes de la note de dépense.

Les deux sont faciles à implémenter.

@eheliot12 un avis ?

**Comment by eheliot12** [comment]
je prefere A, on traitera dans la prochaine release #556 et on remettra a ce moment-la cette variable
