### ISSUE TITLE
test 4.2 / devis / validation document

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#885]
![image](https://user-images.githubusercontent.com/33490126/48613355-c59e1e00-e98b-11e8-9c14-3238711f5905.png)

il ne se passe rien sur le bouton de validation du document

**Comment by sbodrero** [comment]
@eheliot12 peux-tu me préciser quelques étapes pour reproduire ce bug s'il te plaît. Merci.

**Comment by sbodrero** [comment]
@eheliot12 Le souci intervient bien côté entrepreneur ?

**Comment by eheliot12** [comment]
non, c'est au moment de la validation donc ea ou admin
