### ISSUE TITLE
test 4.2 / gestion affaire : creation/transformation en affaire

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#890]
* en formation je cree un devis, de type affaire formation, mais l'affaire n'est pas générée, ca reste un devis simple, il faut générer une affaire apres validation du devis. c'est bien le fonctionnement attendu ?
* j'ai cree un type d'affaire sap, dans un projet classique, dans lequel sap est autorise, je peux effectivement creer des devis sap, mais pas moyen de les transformer en affaire. on a seulement une gestion des repertoires. fonctionnement attendu ?

**Comment by tonthon** [comment]
Oui, c'est le fonctionnement attendu.

Le critère d'affichage de la liste des affaires est le type de projet, si il est égal à "défaut" on présente les documents rangés par dossiers (fonctionnement historique) dans le cas contraire, on présente la liste des affaires.

**Comment by eheliot12** [comment]
ok
il est donc recommandable de ne pas autoriser des affaires complexes dans projet classique.
