### ISSUE TITLE
test4.2 : Plusieurs titres de pages manquants (`<title>`)

### ISSUE THREAD

**Issue by JocelynDelalande** [CroissanceCommune/autonomie#904]
Il s'agit d'une régression (pas de souci en 4.1)

## Contexte

1. Se connecter comme `user_172` (ou autre j'imagine)
2. Aller sur une des pages suivantes : 
  -  « mon compte » https://autonomie-preprod.majerti.fr/users/251
  - https://autonomie-preprod.majerti.fr/projects/52404/phases 
 - /company/78/251/expenses

## Ce qui devrait se passer

Mon navigateur devrait avoir un titre d'onglet / fenêtre  (balise `<title>`)

## Ce qui se passe

![image](https://user-images.githubusercontent.com/429633/48628690-19bef780-e9b8-11e8-849d-fb4249dfe4f2.png)

## Environnement logiciel

* versions d'autonomie concernées : 4.2

**Comment by tonthon** [comment]
La variable title du contexte de templating est utilisée pour définir le titre de la page.
Dans le cas des layouts user/projet/business, ce title est également utilisé en entête des panels lorsqu'il est renseigné, il faudrait certainement revoir ce morceau là.

**Comment by JocelynDelalande** [comment]
J'ai une branche locale sur ce thème, je poursuis lundi.
