### ISSUE TITLE
test4.2 : Libellé «   Documents affectés à aucun dossier  »

### ISSUE THREAD

**Issue by JocelynDelalande** [CroissanceCommune/autonomie#907]
Pas très français, et long.

![image](https://user-images.githubusercontent.com/429633/48629834-fba6c680-e9ba-11e8-821c-869b4285057c.png)

**Comment by eheliot12** [comment]
en français cela donne "documents non-affectés à un dossier"
"documents" peut suffire

**Comment by paul-kilya** [comment]
On peut même ne rien mettre du tout non ? Et éviter de parler de "documents" pour les devis/factures du coup.

Pour moi on pourrait même virer le cadre pour avoir direct les tableaux.

**Comment by eheliot12** [comment]
on peut essayer

**Comment by JocelynDelalande** [comment]
> Pour moi on pourrait même virer le cadre pour avoir direct les tableaux.

J'essaye ça. Il y a un autre petit bug d'ergonomie les gros boutons « créer un devis » / « créer une facture » n'apparaissent que si il y a déjà au moins un devis/facture:

![image](https://user-images.githubusercontent.com/429633/48702126-62f98c00-ebf0-11e8-99ba-5eaccbe98042.png)


Sinon on a ça 

![image](https://user-images.githubusercontent.com/429633/48702095-49584480-ebf0-11e8-8468-31a19f31fd1d.png)

(ce ticket est en train de dériver…)

**Comment by eheliot12** [comment]
oui ca derive, 
le comportement est different suivant affaire classique, ou chantier/convention
landing page d'un projet convention
![image](https://user-images.githubusercontent.com/33490126/48703603-7f97c300-ebf4-11e8-8bb7-7b570b813f2c.png)

**Comment by JocelynDelalande** [comment]
> le comportement est different suivant affaire classique, ou chantier/convention
> landing page d'un projet convention

Bien vu, j'ouvre un ticket pour ça.

**Comment by JocelynDelalande** [comment]
cf solution proposée et captures d'écran sur #926
