### ISSUE TITLE
Harmoniser termes « documents » et « fichiers » sur la vue projet

### ISSUE THREAD

**Issue by JocelynDelalande** [CroissanceCommune/autonomie#912]
![image](https://user-images.githubusercontent.com/429633/48638957-60215000-e9d2-11e8-98c2-794adb7427af.png)

![image](https://user-images.githubusercontent.com/429633/48638968-6b747b80-e9d2-11e8-9e45-4c29b96f28c9.png)

On manque de cohérence sur les termes « documents » et « fichiers ». Notamment ce que désigne document dans le contexte du projet n'est pas clair :

- les devis/factures/avoirs uniquement ?
- les fichiers attachés ?

À harmoniser à mon avis. cf aussi discussion chat https://chat.cooperer.coop/group/projet_erp?msg=qx8WHrjp4XQRWSNTh

**Comment by eheliot12** [comment]
Pour l'utilisateur, il me semble que "documents" fait référence à tout document qui est dans un format de fichier quelconque. les devis, factures, avoirs finissent par etre disponible en fichier aussi.

On peut garder uniquement le terme documents en terme générique
Néanmoins il faut distinguer les documents créés par autonomie des documents qui ont été chargés par les utilisateurs

**Comment by JocelynDelalande** [comment]
> On peut garder uniquement le terme documents en terme générique
> 
> Néanmoins il faut distinguer les documents créés par autonomie
> des documents qui ont été chargés par les utilisateurs
> 

Est-ce que parler de « pièces jointes » ou « fichiers attachés »
pour les fichiers chargés par l'utilisateur ne serait pas
quelque-chose d'assez clair ?

Le fait que c'est des termes que l'on manipule avec les mails au
quotidien aiderait à la compréhension.

**Comment by JocelynDelalande** [comment]
cf solution proposée et captures d'écran sur #926 

J'ai essayé de 

- faire avec des termes déjà existants dans le logiciels (me contentant d'harmoniser)
- prendre en compte cette discussion
- privilégier l'explicite au générique
- ne pas y passer des heures
