### ISSUE TITLE
test4.2 Crash sur documents -> mes documents

### ISSUE THREAD

**Issue by JocelynDelalande** [CroissanceCommune/autonomie#913]
## Contexte
Quelles actions a-t-on effectuées ou doit-on effectuer pour que le bogue se manifeste ?

Quelles étapes :

1. Se connecter 
2. Cliquer sur Documents -> Mes documents

## Ce qui devrait se passer

Voir quelque-chose.

## Ce qui se passe

https://autonomie-preprod.majerti.fr/users/251/userdatas/mydocuments
Erreur 500

en local ça dit :

```
OSError: [Errno 2] Aucun fichier ou dossier de ce type: '/userdatas/mydocuments.mako'
```

## Environnement logiciel

* versions d'autonomie concernées 4.2

**Comment by sbodrero** [comment]
C'est corrigé avec la PR #892 en attente

**Comment by JocelynDelalande** [comment]
#892 n'est pas une PR

**Comment by sbodrero** [comment]
Oups il s'agit de la PR 899 
https://github.com/CroissanceCommune/autonomie/commit/7bd02559aa0826017045ee1571a074e4a9828450#diff-ee0ab46086da8e33c31931fcf072e809R126

**Comment by JocelynDelalande** [comment]
Corrigé par #899
