### ISSUE TITLE
test4.2 Deux entrées de menu en surbrillance sur 

### ISSUE THREAD

**Issue by JocelynDelalande** [CroissanceCommune/autonomie#915]
![image](https://user-images.githubusercontent.com/429633/48639814-0cfccc80-e9d5-11e8-8340-4e7a612e50e3.png)

Sur https://autonomie-preprod.majerti.fr/users/251/holidays : il y a deux entrées grisées.

C'est une régression, ce bug n'est pas présent en 4.1.

**Comment by tonthon** [comment]
la détection de l'activité devrait être revu, pour l'instant 

- /users/251 (mon compte) est contenu dans /users/251/holidays donc actif
- /users/251/holidays (mes congés) est également actif
