### ISSUE TITLE
mini fenêtre de demande d'information

### ISSUE THREAD

**Issue by feth** [CroissanceCommune/autonomie#92]
Dans le cadre de la saisie dans autonomie d'informations personnelles, souvent insuffisamment renseignées, on a pu évoquer la possibilité d'inciter fortement les utilisateurs à saisir les informations manquantes en affichant une mini fenêtre en avant plan permettant de saisir rapidement les informations manquantes, et ainsi permettre aux CAE de disposer de données démographiques indispensables à leur mission.

**Comment by eheliot12** [comment]
les données demographiques sont dans la gestion sociale, a charge de l'equipe de les collecter et de respecter ce que la CAE definit pour etre conforme rgpd
