### ISSUE TITLE
gestion sociale / portefeuille documents / dossier parent

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#922]
![image](https://user-images.githubusercontent.com/33490126/48695812-70a71580-ebe0-11e8-955b-fdf87a2889a7.png)

quel est l'usage du "document parent" ? comment le modifier ?

au moment du téléchargement, ou de la modification du document, on n'y accède pas

**Comment by tonthon** [comment]
Cette colonne ne devrait pas apparaitre
