### ISSUE TITLE
test4.2 : Affichage des affaires « convention de formation » différent des autres

### ISSUE THREAD

**Issue by JocelynDelalande** [CroissanceCommune/autonomie#925]
Suite au retour d' @eheliot12 https://github.com/CroissanceCommune/autonomie/issues/907#issuecomment-439857618

Pour un projet de type « convention de formation », l'affichage et les termes sont légèrement différents, est-ce volontaire ?

Convention de formation :

![image](https://user-images.githubusercontent.com/429633/48712776-e033f980-ec0e-11e8-8b03-1e67916963a8.png)

Autre type de projet :

![image](https://user-images.githubusercontent.com/429633/48712845-196c6980-ec0f-11e8-91f6-11f76acabb73.png)

## Quelles différences ?

Particularité convention de formation :

- « liste des affaires » au lieu de « devis/factures par dossier »
- pas de breadcrumb
- pas de rangement par dossier
- peut-être d'autres qui m'échappent.

Les chantiers ne semblent pas impacté (affichage similaire aux affaires simples).

:question: a quel point est-ce volontaire, à quel point est-ce un bug :question:

**Comment by tonthon** [comment]
Le rangement par affaire et non par dossier est volontaire.
Le fait que ce ne soit pas le cas pour les chantiers serait un bug.

Le problème du breadcrumb est corrigé (PR en cours).

**Comment by tonthon** [comment]
Dans les chantiers on a bien le même affichage quand pour les formations.
Pour moi c'est bon.
