### ISSUE TITLE
Test 4.2 : exporter les émargements ne contient pas les formateurs

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#932]
Les formateurs ne sont plus présents dans le fichier.

Une solution serait de rajouter le champ description dans l'export

**Comment by sbodrero** [comment]
@tonthon est ce qu'il s'agit bien des exports émargements du type du document ci-après ?

[atelier_13_12_2018_63452 (4).pdf](https://github.com/CroissanceCommune/autonomie/files/2610753/atelier_13_12_2018_63452.4.pdf)

**Comment by JocelynDelalande** [comment]
J'ai l'impression que l'on parle d'un problème de migration de données : les ateliers renseignés en pre-4.2 avaient un champ texte « trainers » pour stocker les formateurs. Avec la 4.2 le contenu de ce champ a atteri dans le nouveau champ « description ». Ce champ n’apparaît pas dans les exports. Par ailleurs, nous avons un champ structuré (pointant vers des utilisateur·ice·s) « trainers », qui est initialisé vide pour les ateliers saisis avant ce changement de modèle.

> @tonthon est ce qu'il s'agit bien des exports émargements du type du document ci-après ?

@sbodrero je pense que le problème se pose à la fois pour l'export tabulaire, bouton « Exporter émargements » et pour l'export PDF dont tu parle.

Je ne sais pas trop à quel point il faut effectivement gérer ce cas de migration, ou bien laisser tel quel : avoir la description dans le CSV n'est pas spécialement intéressant, et l'avoir dans la feuille d'émargement semble inutile (le champ description sert à être un peu verbeux si on le souhaite).

Deux questions :

1. :question: **à terme** : veut-on faire apparaître le champ description dans les différents exports 
2. :question:  **maintenant** : est-ce acceptable de demander aux utilisateur·ice·s, pour les ateliers saisi en pre-4.2 et exporté en post-4.2, de remplir le champ « formateur·ice·s » à la main (les feuilles d'émargement sont de toutes façons imprimées pour être signées).

Si on ne veut pas 1. pour les PDF mais que l'on veut prendre soin des utilisateur·ice·s, on peut toujours faire un hack temporaire : si le champ « formateur·ice·s » n'est pas rempli, et qu'on reconnait un contenu « migré » dans le champ description, on affiche le contenu du champ description.  Et dans quelques mois, on retire ce hack.

**Comment by JocelynDelalande** [comment]
> aujourd'hui les feuilles sont imprimees et signees a la main. donc pb de migration : on explique qu'il faut modifier les animateurs, ou rajouter a la main les infos sur la fiche

OK. Donc à mettre dans les release notes ?

> demain, on utilisera de la signature manuscrite en copier/coller en particulier pour les animateurs et pour les membres de la cae -> faudra que ca passe, un tableau des animateurs plutot que tout sur une ligne me semblerait mieux.

OK. J'ouvre un ticket.

(et les signatures formateur en bas du doc plutôt qu'en haut).

> sur l'export en masse, qui sert a faire de la stat, la colonne formateur peut etre changee par une colonne role (apprenant / formateur)

Ah ok, je trouve ça surprenant d'avoir dans le même tableau les émargements stagiaires et formateurs.

Si on fait ça,  est-ce qu'on ferait apparaître les 3 rôles apprenant / formateur / gestionnaire ou on laisse le gestionnaire en dehors de cet export ?

**Comment by eheliot12** [comment]
le gestionnaire, ne me semble pas interessant, on va faire des stats
* qui a suivi quoi et pour combien de temps : aspect apprenant
* qui était present a quoi : aspect financeur public
* qui a anime quoi : aspect facturation interne, et financeur

**Comment by JocelynDelalande** [comment]
Tickets ouverts #952 #953 je propose de poursuivre les discussions sur ces deux points plutôt sur ces tickets.

@eheliot12 On peut clore ce ticket du coup ? Est-ce que je le laisse ouvert pour penser à àjouter une note sur tes release notes ?

**Comment by eheliot12** [comment]
release note ok
