### ISSUE TITLE
test 4.2 / atelier acces feuille emargement

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#944]
le formateur non admin recoit un acces refuse si il essiae d'acceder a la feuille d'emargement par le lien, fonctionne pour l'admin
![image](https://user-images.githubusercontent.com/33490126/48835355-34aab680-ed80-11e8-91b9-f53d3aa6c0d0.png)

**Comment by sbodrero** [comment]
@eheliot12 tu peux me donner le user (formateur non admin) que tu utilises pour cet exemple s'il te plaît.
Merci.

**Comment by eheliot12** [comment]
user_95

**Comment by sbodrero** [comment]
> user_95

Merci

**Comment by sbodrero** [comment]
Lorsque je j'affiche la liste des workshops via l'utilisateur user_95 je n'ai pas la même url https://autonomie-preprod.majerti.fr/company/138/workshops

Et à partir de cette page les liens n'existes pas.

**Comment by sbodrero** [comment]
> il y a les ateliers et il y a les ateliers ;)
> 
> * ceux auxquels je participe en tant qu'es sont accompagnement/atelier (ton url)
> * ceux que j'organise ou anime sont outils metier/organisation atelier (mon url)

Ok merci pour la précision ;-)

**Comment by JocelynDelalande** [comment]
@eheliot12 Pour l'heure l'idée serait de donner ces droits de voir les émargements tant au gestionnaire de l'atelier qu'à ses formateur·ice·s ou uniquement au gestionnaire ?

**Comment by eheliot12** [comment]
a tous les animateurs et gestionnaires. c'est les animateurs qui font signer les feuilles
