### ISSUE TITLE
test 4.2 / injection depuis catalogue - formation/ouvrage, les produits ne sont pas ajoutés

### ISSUE THREAD

**Issue by eheliot12** [CroissanceCommune/autonomie#958]
injection d'une formation comprenant 2 produits
* via editer, les produits ne sont pas ajoutes
* via inserer, les produits sont bien ajoutes

https://autonomie-demo.delalande.fr/invoices/63419

idem avec un ouvrage non formation

**Comment by sbodrero** [comment]
@eheliot12 je viens de discuter de l'issue avec @tonthon et à la base il n'est pas question de modifier l'ouvrage avant de l'insérer mais plutôt d'insérer l'ouvrage (option qui fonctionne) et de modifier ensuite la caractéristiques (titre, description, produits). Du coup l'issue pourrait se muer en "Supprimer du bouton "Éditer comme un nouvel élément" du formulaire d'insertion d'ouvrage dans les devis/factures". Qu'en penses-tu ?

**Comment by eheliot12** [comment]
ok. ca resoud la discordance fonctionnelle
perso je trouve que 2 boutons d'action pour faire la meme chose à un clic pres, c'est un peu trop

**Comment by sbodrero** [comment]
Sur le même principe lorsqu'on souhaite ajouter plusieurs produits à un devis/facture l'option "Éditer comme un nouvel élément" prend en compte un seul des deux produits qui vient s'ajouter au devis après update. 
C'est tout à fait logique de pouvoir modifier qu'un seul produit et pour apporter plus de clarté à l'utilisateur on pourrait griser le bouton "Éditer comme un nouvel élément" si l'utilisateur sélectionne plusieurs produits.

**Comment by eheliot12** [comment]
je pense de plus en plus qu'un seul bouton va suffire

**Comment by sbodrero** [comment]
C'est vrai que c'est plutôt le comportement "habituel" => Ajouter puis modifier
